"""Tests for domain.collection_label.

The type label appended to a Steam collection name under the ``by_label``
naming mode, its absence for a standard collection, and the Steam name each
naming mode builds from it; where else the strings are spelled is
``docs/architecture/steam-non-steam-shortcuts.md`` § Collection naming mode.
No label may contain ``]`` (it sits inside the ``RomM: [<name> (<label>)]``
bracket pair the frontend reconcile parses).
"""

from __future__ import annotations

import pytest

from domain.collection_label import collection_label, steam_collection_key

# The known (kind, virtual_type) → label mapping for every labelled kind.
_KNOWN_CASES = [
    ("smart", None, "Smart"),
    ("virtual", "franchise", "Franchise"),
    ("virtual", "collection", "IGDB Collection"),
]


class TestKnownLabels:
    @pytest.mark.parametrize(("kind", "virtual_type", "expected"), _KNOWN_CASES)
    def test_known_kind_and_type_map_to_their_label(self, kind, virtual_type, expected):
        assert collection_label(kind, virtual_type) == expected

    def test_standard_has_no_label(self):
        assert collection_label("standard", None) is None

    def test_standard_ignores_a_stray_virtual_type(self):
        # A non-virtual kind never consults virtual_type — a spurious value is harmless.
        assert collection_label("standard", "franchise") is None

    def test_smart_ignores_a_stray_virtual_type(self):
        assert collection_label("smart", "collection") == "Smart"


class TestVirtualFallback:
    """A virtual collection with a missing/unrecognised type degrades to 'Autogenerated'."""

    def test_virtual_without_type_falls_back(self):
        assert collection_label("virtual", None) == "Autogenerated"

    def test_virtual_with_unknown_type_falls_back(self):
        # A virtual type Tender does not sync (genre/company/mode) → 'Autogenerated'.
        assert collection_label("virtual", "genre") == "Autogenerated"


class TestUnknownKindFallback:
    def test_unknown_kind_capitalised(self):
        assert collection_label("weird", None) == "Weird"

    def test_empty_kind_degrades_to_collection(self):
        assert collection_label("", None) == "Collection"


class TestNoClosingBracketInLabel:
    """A label must never contain ']' — it would truncate the reconcile name-parse."""

    @pytest.mark.parametrize(("kind", "virtual_type", "expected"), _KNOWN_CASES)
    def test_known_labels_have_no_closing_bracket(self, kind, virtual_type, expected):
        label = collection_label(kind, virtual_type)
        assert label is not None
        assert "]" not in label

    @pytest.mark.parametrize(
        ("kind", "virtual_type"),
        [("virtual", None), ("virtual", "genre"), ("weird", None), ("", None)],
    )
    def test_fallback_labels_have_no_closing_bracket(self, kind, virtual_type):
        label = collection_label(kind, virtual_type)
        assert label is not None
        assert "]" not in label


class TestSteamCollectionKey:
    @pytest.mark.parametrize(("kind", "virtual_type", "expected"), _KNOWN_CASES)
    def test_by_label_appends_the_label(self, kind, virtual_type, expected):
        assert steam_collection_key("Mario", kind, virtual_type, "by_label") == f"Mario ({expected})"

    def test_by_label_leaves_a_standard_collection_bare(self):
        assert steam_collection_key("Mario", "standard", None, "by_label") == "Mario"

    @pytest.mark.parametrize(("kind", "virtual_type", "_label"), _KNOWN_CASES)
    def test_merge_is_the_bare_name_for_every_kind(self, kind, virtual_type, _label):
        assert steam_collection_key("Mario", kind, virtual_type, "merge") == "Mario"

    def test_an_unknown_mode_reads_as_merge(self):
        assert steam_collection_key("Mario", "smart", None, "sideways") == "Mario"
