"""Platform translation — a public platform id in, atlas's vocabulary out, and back.

The split follows the boundary rule exactly. Which public identities a
*platform* has — its IGDB platform (numeric id first: IGDB slugs drift under a
stable id), its libretro database names, the two scraper ids ES-DE itself
maps — is written nowhere on a machine, so it ships here as world knowledge:
versioned, source-cited, regenerated by ``scripts/generate_platform_crosswalk.py``
from pinned revisions. Which platform a *system* belongs to is on the machine —
every catalogue system carries a ``<platform>`` tag — and is read live by the
resolvers, never tabled.

This module owns only the world-knowledge half: the crosswalk loader and the
pure lookups over it. The machine-qualified questions (which systems of *this
installation* answer to an IGDB id, and with what status) live on the
installation handles, because only a handle can answer them.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from ._data import packaged_text

PLATFORM_CROSSWALK_SCHEMA = 1

# The degradations a platform question states — structured, never free-text-only.
# "unmapped": the question's subject corresponds to no platform knowledge — a
# public id no crosswalk row carries, or a system name neither this machine nor
# the vocabulary knows; data names what was asked. "unknown": a catalogue's own
# <platform> token is outside the platform vocabulary — the state ES-DE itself
# warns about and drops (SystemData.cpp:1096-1098 @ v3.4.1); atlas states it.
# "scraping-ignored": the catalogue tags the system `ignore`, ES-DE's opt-out —
# deliberately no platform, which is a different fact than an empty tag.
CAVEAT_PLATFORM_UNMAPPED = "platform-unmapped"
CAVEAT_PLATFORM_UNKNOWN = "platform-unknown"
CAVEAT_PLATFORM_SCRAPING_IGNORED = "platform-scraping-ignored"

# The public vocabularies a platform question may name — a closed set: the
# crosswalk's columns, nothing else. RomM's or any other server product's own
# slugs are deliberately not among them; such a product publishes IGDB
# identifiers itself, and its private namespace migrates with its releases.
KNOWN_PLATFORM_VOCABULARIES = ("igdb", "libretro", "screenscraper", "thegamesdb")


@dataclass(frozen=True, slots=True)
class IgdbIdentity:
    """One IGDB platform as recorded at the pinned revision.

    ``id`` is the stable key — IGDB renamed platform 117's slug from
    ``philips-cd-i`` to ``philips-cdi`` under the same id, so the slug and
    name ride along as conveniences recorded at the pin, never as keys.
    """

    id: int
    """The stable IGDB platform key, and the one field to match on — IGDB re-spells slugs
    under an unchanged id.
    """
    slug: str
    """IGDB's slug for the platform as recorded at the pinned revision — a convenience,
    never a key.
    """
    name: str
    """IGDB's display name for the platform as recorded at the pinned revision — a
    convenience, never a key.
    """


@dataclass(frozen=True, slots=True)
class PlatformIdentities:
    """One ES-DE platform's public identities — empty columns are decided nulls.

    The semantics of the identity lists: the public platforms whose games
    belong on this ES-DE platform, family-canonical only. Empty means the
    pinned sources record no identity (game engines, fantasy consoles,
    hardware IGDB does not carry) — a reviewed absence, not a gap.
    """

    platform: str
    """The ES-DE platform tag these identities belong to."""
    igdb: tuple[IgdbIdentity, ...]
    """The IGDB platforms whose games belong on this ES-DE platform, family-canonical
    only — empty is a reviewed absence rather than a gap.
    """
    libretro: tuple[str, ...]
    """The libretro platform names for this ES-DE platform, family-canonical only — empty
    is a reviewed absence rather than a gap.
    """
    screenscraper: int | None
    """The ScreenScraper system id for this ES-DE platform, and ``None`` where the pinned
    sources record none.
    """
    thegamesdb: int | None
    """The TheGamesDB platform id for this ES-DE platform, and ``None`` where the pinned
    sources record none.
    """


def _expect_str(value: Any, where: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{where}: expected a non-empty string, got {value!r}")
    return value


def _expect_int_or_none(value: Any, where: str) -> int | None:
    if value is not None and not isinstance(value, int):
        raise ValueError(f"{where}: expected an integer or null, got {value!r}")
    return value


def _igdb_identity(entry: Any, where: str) -> IgdbIdentity:
    if not isinstance(entry, dict) or set(entry) != {"id", "slug", "name"}:
        raise ValueError(f"{where}: an igdb identity names exactly id, slug and name, got {entry!r}")
    if not isinstance(entry["id"], int):
        raise ValueError(f"{where}: id must be an integer, got {entry['id']!r}")
    return IgdbIdentity(
        id=entry["id"],
        slug=_expect_str(entry["slug"], f"{where}: slug"),
        name=_expect_str(entry["name"], f"{where}: name"),
    )


def _identities(platform: str, entry: Any) -> PlatformIdentities:
    where = f"platform crosswalk {platform!r}"
    if not isinstance(entry, dict) or set(entry) != {
        "comment",
        "igdb",
        "libretro",
        "screenscraper",
        "thegamesdb",
    }:
        raise ValueError(
            f"{where}: a row names exactly comment, igdb, libretro, screenscraper "
            f"and thegamesdb, got {entry!r}"
        )
    igdb_raw = entry["igdb"]
    libretro_raw = entry["libretro"]
    if not isinstance(igdb_raw, list) or not isinstance(libretro_raw, list):
        raise ValueError(f"{where}: igdb and libretro must be lists")
    igdb = tuple(_igdb_identity(e, f"{where}: igdb[{i}]") for i, e in enumerate(igdb_raw))
    if len({identity.id for identity in igdb}) != len(igdb):
        raise ValueError(f"{where}: igdb repeats an id")
    return PlatformIdentities(
        platform=platform,
        igdb=igdb,
        libretro=tuple(_expect_str(e, f"{where}: libretro[{i}]") for i, e in enumerate(libretro_raw)),
        screenscraper=_expect_int_or_none(entry["screenscraper"], f"{where}: screenscraper"),
        thegamesdb=_expect_int_or_none(entry["thegamesdb"], f"{where}: thegamesdb"),
    )


def load_platform_crosswalk(text: str | None = None) -> dict[str, PlatformIdentities]:
    """Load the packaged crosswalk (or *text* when supplied, for tests) — fail-closed.

    Every refusal here is an identity a question could otherwise be answered
    out of: an unreadable schema, a malformed row and a repeated IGDB id each
    fail the load rather than shipping a table whose own account of itself
    does not add up.
    """
    if text is None:
        text = packaged_text("platform_ids_crosswalk.json")
    raw = json.loads(text)
    if not isinstance(raw, dict) or raw.get("schema") != PLATFORM_CROSSWALK_SCHEMA:
        raise ValueError(
            f"platform_ids_crosswalk: unsupported schema "
            f"{raw.get('schema') if isinstance(raw, dict) else None!r} "
            f"(this atlas reads schema {PLATFORM_CROSSWALK_SCHEMA})"
        )
    platforms = raw.get("platforms")
    if not isinstance(platforms, dict) or not platforms:
        raise ValueError("platform_ids_crosswalk: 'platforms' must be a non-empty object")
    return {
        _expect_str(platform, "platform key"): _identities(platform, entry)
        for platform, entry in platforms.items()
    }


_PACKAGED: dict[str, PlatformIdentities] | None = None


def _crosswalk() -> dict[str, PlatformIdentities]:
    global _PACKAGED
    if _PACKAGED is None:
        _PACKAGED = load_platform_crosswalk()
    return _PACKAGED


def known_platforms() -> tuple[str, ...]:
    """Every ES-DE platform id the crosswalk carries, sorted — the tag vocabulary."""
    return tuple(sorted(_crosswalk()))


def platform_identities(platform: str) -> PlatformIdentities | None:
    """The public identities of one platform id, or ``None`` — no fuzzy matching.

    ``None`` is "not a platform id" (an unknown tag, a typo, the ``ignore``
    sentinel); a *row with empty columns* is the different statement "a real
    platform the pinned sources record no identity for".
    """
    return _crosswalk().get(platform)


# Only the type is refused: the empty string is a question with an answer
# ("no platform corresponds"), so a platform value is not an _expect_str one.
def _expect_platform_value(value: Any, vocabulary: str) -> str:
    if not isinstance(value, str):
        raise ValueError(
            f"platform value for {vocabulary!r}: expected a string, got {value!r} "
            f"(a numeric id is asked for as its decimal string)"
        )
    return value


def platforms_for(vocabulary: str, value: str) -> tuple[str, ...]:
    """The ES-DE platforms whose identities carry *value* in *vocabulary*, sorted.

    *value* is a string in every vocabulary: a numeric id passes as its decimal
    string, so a consumer holding IGDB's numeric ``igdb_id`` asks with
    ``str(igdb_id)``. ``igdb`` matches that id or the slug, case-insensitively —
    the id is the stable key, the slug a drifting convenience. ``libretro``
    matches the database name exactly as libretro spells it ("Nintendo - Game
    Boy Advance"). ``screenscraper`` and ``thegamesdb`` match their numeric
    ids as digits. An unknown *vocabulary* raises — the set is this module's
    own and closed (:data:`KNOWN_PLATFORM_VOCABULARIES`) — and so does a
    non-string *value*, stated rather than quietly coerced; an unmatched
    *value* answers the empty tuple, because "no platform corresponds" is an
    answer.
    """
    if vocabulary not in KNOWN_PLATFORM_VOCABULARIES:
        raise ValueError(
            f"unknown platform vocabulary {vocabulary!r} "
            f"(one of {', '.join(KNOWN_PLATFORM_VOCABULARIES)})"
        )
    wanted = _expect_platform_value(value, vocabulary).strip()
    matches = [
        platform
        for platform, identities in _crosswalk().items()
        if _matches(identities, vocabulary, wanted)
    ]
    return tuple(sorted(matches))


def _matches(identities: PlatformIdentities, vocabulary: str, value: str) -> bool:
    if vocabulary == "igdb":
        folded = value.casefold()
        return any(value == str(i.id) or folded == i.slug.casefold() for i in identities.igdb)
    if vocabulary == "libretro":
        return value in identities.libretro
    number = identities.screenscraper if vocabulary == "screenscraper" else identities.thegamesdb
    return number is not None and value == str(number)
