"""emu-atlas — the map of where emulators keep things.

A resolver, not a lookup: for any emulator installation on a machine, atlas
answers which configs govern it and where saves and BIOS actually live — by
reading the running machine the way the emulator does. Phase 1 covers RetroArch
across the RetroDECK, EmuDeck and bare (Flatpak or native) arrangements,
plus firmware.

Two entry points, per DESIGN.md:

- :func:`atlas.detect` finds what is installed and returns installation handles;
- every question is asked of a handle —
  ``installation.savefile_location(content_path=..., core_so=...)``,
  ``installation.firmware_for_core("mgba_libretro.so")``,
  ``installation.firmware_for_system("gba")``,
  ``installation.firmware_inventory()``,
  ``installation.identify_firmware(md5=...)``.

The question's subject may be positional — the core, the system — while every
modifier stays keyword-only.

Choosing a handle is optional: :func:`atlas.every_installation` puts the same
questions to every detected installation at once and answers each labelled with
the handle it came from, so a machine carrying two arrangements gives two true
answers instead of a silently chosen winner.

One thing here is the host's to grant rather than atlas's to require. The zstd
codec that opens an AppImage is discovered, never depended on:
:func:`atlas.register_zstd_provider` hands over the module a host already has,
which is what a host that vendors it under its own root needs, and
:func:`atlas.zstd_provider` says which provider a zstd image would go through
here and whether a host handed it over (:class:`atlas.ZstdProvider`). All three
are re-exported here from ``atlas.squashfs``; none adds a dependency.

**What this namespace is.** Everything below is the consumer API: the two entry
points, the handles they answer with, every answer type, the vocabularies those
answers speak, the serializers that turn an answer into plain data, and the one
capability a host grants rather than atlas requiring it. If you are writing a
client, you never need to import from a submodule.

**What it deliberately is not.** The machine seam, the config and catalogue
parsers, the packaged-data loaders and the module-level resolver functions are
port and tooling surface: real, documented, and imported from their own modules
(``from atlas.machine import FixtureMachine``). They are not here because a
consumer choosing between ``atlas.firmware_for_core(machine, context, ...)``
and ``installation.firmware_for_core(...)`` is a consumer who can pick the
wrong one. See DESIGN.md, "The two tiers", and docs/architecture.md for the map.
"""

from __future__ import annotations

# pyproject.toml is the one version source; this line is its second spelling,
# for the vendored directory copy that has no dist-info to answer from. A
# second spelling is acceptable only mechanized: release-please rewrites it at
# release time (the trailing annotation marks the line for its generic updater,
# wired by the `extra-files` entry in release-please-config.json), and
# tests/test_version.py holds it equal to pyproject — CI's package job holds
# dist-info to pyproject in a clean venv — so drift is a red test, not a
# silent fork.
__version__ = "0.12.0"  # x-release-please-version

# --- The two entry points, and the aggregate over them -----------------------
from .detect import detect
from .every_installation import EveryInstallation, InstallationAnswer, every_installation

# --- The one capability a host grants, rather than atlas requiring it --------
# The zstd codec an AppImage read may need is discovered, never imported as a
# dependency; a host whose own packaging holds it hands the module over here.
from .squashfs import ZstdProvider, register_zstd_provider, zstd_provider

# --- The vocabulary those questions take -------------------------------------
# ES-DE's system names, and the two ways to check a name against them. A
# consumer holding some other product's identifiers owns that mapping and
# validates it here — atlas carries no foreign vocabulary (atlas/systems.py).
from .systems import from_esde_system, known_systems, vocabulary_platform_tags
from .platforms import (
    CAVEAT_PLATFORM_SCRAPING_IGNORED,
    CAVEAT_PLATFORM_UNKNOWN,
    CAVEAT_PLATFORM_UNMAPPED,
    KNOWN_PLATFORM_VOCABULARIES,
    IgdbIdentity,
    PlatformIdentities,
    known_platforms,
    load_platform_crosswalk,
    platform_identities,
    platforms_for,
)

# --- The handles every question is asked of ----------------------------------
from .installations import (
    EmuDeck,
    Installation,
    BareRetroArchNative,
    RetroDeck,
    BareRetroArchFlatpak,
)

# --- The answers ------------------------------------------------------------
from .contract import (
    catalogue_contract,
    mod_answer_contract,
    mod_placement_contract,
    soft_patch_answer_contract,
    soft_patch_contract,
    texture_answer_contract,
    texture_placement_contract,
    savestate_absence_contract,
    savestate_answer_contract,
    savestate_placement_contract,
    rom_placement_contract,
    emulator_contract,
    firmware_contract,
    health_contract,
    identification_contract,
    installation_answers_contract,
    installation_contract,
    launchable_contract,
    platform_systems_contract,
    savefile_answer_contract,
    savefile_placement_contract,
    system_platforms_contract,
    systems_contract,
    unresolved_contract,
)
from .firmware import (
    CoreFirmware,
    FirmwareAlternatives,
    FirmwareAnswer,
    FirmwareIdentification,
    FirmwareIdentity,
    FirmwareRequirement,
    RefusedDeclaration,
    SuppliedBy,
    UnclaimedFile,
)
from .installations import (
    CAVEAT_CONFIG_HOME_RELOCATED,
    CAVEAT_FRONTEND_MARKER_MISMATCH,
    CAVEAT_FRONTEND_SETTINGS_UNREADABLE,
    CAVEAT_ROM_PATH_UNDECLARED,
    CAVEAT_ROM_PATH_UNRESOLVED,
    CAVEAT_ARCHIVE_CONTENTS_UNREAD,
    CAVEAT_ENTRY_FORMAT_UNCLAIMED,
    CAVEAT_ENTRY_FORMAT_UNESTABLISHED,
    LAUNCH_VERDICTS,
    PLATFORM_STATUS_ABSENT,
    PLATFORM_STATUS_DECLARED,
    PLATFORM_STATUS_DISABLED,
    PLATFORM_TAGS_CATALOGUE,
    PLATFORM_TAGS_VOCABULARY,
    VERDICT_ENTRY_NOT_ACCEPTED,
    VERDICT_LAUNCHABLE,
    VERDICT_NEEDS_INSTALLATION,
    VERDICT_NOT_ACCEPTED,
    VERDICT_UNKNOWN,
    CatalogueAnswer,
    EmulatorEntry,
    Health,
    LaunchabilityAnswer,
    PlatformSystemMatch,
    PlatformSystemsAnswer,
    RomPlacement,
    SystemPlatformsAnswer,
    SystemsAnswer,
)
from .launch_formats import (
    InstallFirstFormat,
    StandaloneLaunchCard,
    load_launch_formats,
    load_standalone_launch,
    lookup_install_first,
    lookup_standalone_launch,
)
from .esde import esde_extension
from .placement import (
    Caveat,
    FileGroup,
    FileSet,
    Granularity,
    ModeAlternative,
    OptionReading,
    ModPlacement,
    ModTree,
    SavefilePlacement,
    SavestateAbsence,
    SavestatePlacement,
    ScreenshotPlacement,
    SoftPatchAnswer,
    SoftPatchCandidate,
    TexturePlacement,
    Unresolved,
)

# --- The vocabularies those answers speak ------------------------------------
# Closed sets, as types and as constants: a client branches on the value, and
# annotates with the type. The seam's own two (`PathKind`, `ReadStatus`) are
# here because answers carry them — a requirement's `found` is a path kind, a
# health finding's `status` is a read status.
from .esde import KIND_LIBRETRO, KIND_STANDALONE
from .retroarch_cfg import (
    CFG_LAYER_CONTENT_DIR_OVERRIDE,
    CFG_LAYER_CORE_OVERRIDE,
    CFG_LAYER_GAME_OVERRIDE,
    CFG_LAYER_GLOBAL,
    CFG_LAYER_KINDS,
)
from .evidence import CAVEAT_ARRANGEMENT_UNVERIFIED, CAVEAT_ARRANGEMENT_VERSION_DRIFTED
from .firmware import (
    ARCHIVE_CORE_BUNDLED,
    ARCHIVE_ROMSET,
    CAVEAT_EMULATOR_CATALOGUE_EXCLUSIVE,
    CAVEAT_EMULATOR_CATALOGUE_SEALED,
    CAVEAT_EMULATOR_CATALOGUE_UNAVAILABLE,
    CAVEAT_EMULATOR_CATALOGUE_UNESTABLISHED,
    CAVEAT_EMULATOR_CATALOGUE_UNREADABLE,
    CAVEAT_EMULATOR_LIST_DERIVED,
    CAVEAT_CORE_DIR_UNRESOLVED,
    CAVEAT_CORE_ENUMERATION_INCOMPLETE,
    CAVEAT_CORE_INFO_UNREADABLE,
    CAVEAT_CORE_NOT_INSTALLED,
    CAVEAT_CORE_WITHOUT_SYSTEMNAME,
    CAVEAT_EMULATOR_CONFIG_UNREADABLE,
    CAVEAT_FIRMWARE_BUILTIN_REPLACEMENT,
    CAVEAT_FIRMWARE_CONTENT_CONTRADICTORY,
    CAVEAT_FIRMWARE_CONTENT_UNIDENTIFIED,
    CAVEAT_FIRMWARE_CONTENT_UNSTATED,
    CAVEAT_FIRMWARE_IDENTITY_NOT_COMPARABLE,
    CAVEAT_FIRMWARE_IMAGE_AMBIGUOUS,
    CAVEAT_FIRMWARE_IMAGE_CONTRADICTED,
    CAVEAT_FIRMWARE_IMAGE_IDENTIFIED,
    CAVEAT_FIRMWARE_IMAGE_UNLISTED,
    CAVEAT_FIRMWARE_DECLARATION_UNKNOWN,
    CAVEAT_FIRMWARE_PACKAGED_DECLARATION,
    CAVEAT_FIRMWARE_DECLARATION_UNREAD,
    CAVEAT_FIRMWARE_DIRECTORY_HOLDS_NO_CANDIDATE,
    CAVEAT_FIRMWARE_DIRECTORY_HOLDS_NO_IMAGE,
    CAVEAT_FIRMWARE_PATH_ESCAPES_ROOT,
    CAVEAT_FIRMWARE_PATH_INACCESSIBLE,
    CAVEAT_FIRMWARE_PATH_LAUNCH_DEPENDENT,
    CAVEAT_FIRMWARE_PATH_NAMES_NO_FILE,
    CAVEAT_FIRMWARE_PATH_NOT_A_DIRECTORY,
    CAVEAT_FIRMWARE_PATH_OBSTRUCTED,
    CAVEAT_FIRMWARE_PATH_UNRESOLVABLE,
    CAVEAT_FIRMWARE_ROOT_MISSING,
    CAVEAT_FIRMWARE_ROOT_UNUSABLE,
    CAVEAT_FIRMWARE_SCAN_INCOMPLETE,
    CAVEAT_FIRMWARE_SEARCH_UNVERIFIED,
    CAVEAT_FIRMWARE_SUPPLIED_SOURCE_UNREADABLE,
    CAVEAT_FIRMWARE_UNREADABLE,
    CAVEAT_INFO_PATH_UNRESOLVED,
    CAVEAT_NO_FIRMWARE_DECLARATION,
    CAVEAT_NO_FIRMWARE_REQUIREMENT,
    CAVEAT_STANDALONE_UNSUPPORTED,
    CAVEAT_SYSTEM_ASSIGNMENT_DERIVED,
    CAVEAT_SYSTEM_ASSIGNMENT_MAY_HIDE_CORES,
    CAVEAT_SYSTEM_NOT_IN_CATALOGUE,
    CAVEAT_SYSTEM_UNKNOWN,
    CHECKED_MISMATCH,
    CHECKED_NOT_COMPARABLE,
    CHECKED_UNCHECKED,
    CHECKED_UNKNOWN,
    CHECKED_VERIFIED,
    DECLARATION_ABSENT,
    DECLARATION_PACKAGED,
    DECLARATION_READ,
    DECLARATION_UNREADABLE,
    DECLARATION_UNSUPPORTED,
    DECLARED_DIRECTORY,
    DECLARED_FILE,
    IDENTITY_ARCHIVE,
    IDENTITY_FILE,
    NEED_OPTIONAL,
    NEED_REQUIRED,
    SOURCE_CARD,
    SOURCE_NONE,
    SOURCE_OVERRIDE,
    SOURCE_SLUG,
    SOURCE_SYSTEMNAME,
    SYSTEMS_WITHOUT_CATALOGUE_ID,
    ArchiveReason,
    CoreDeclarationState,
    DeclaredKind,
    FirmwareChecked,
    FirmwareIdentityKind,
    FirmwareNeed,
    SystemSource,
)
from .content_tree_wiring import (
    ArrangementWiring,
    WiringRow,
    load_content_tree_wiring,
    lookup_content_tree_wiring,
)
from .distribution_labels import (
    DistributionLabel,
    distribution_label,
    load_distribution_labels,
)
from .distribution_supplied import (
    DistributionSupplied,
    SuppliedEntry,
    load_distribution_supplied,
    lookup_distribution_supplied,
)
from .installations import (
    HEALTH_ISSUE_CATALOGUE_INVALID,
    HEALTH_ISSUE_COMPANION_CONFIG_MISSING,
    HEALTH_ISSUE_CONFIG_UNREADABLE,
    HEALTH_ISSUE_CONTENT_TREE_UNWIRED,
    HEALTH_ISSUE_MARKER_INVALID,
    HEALTH_ISSUE_MARKER_MISSING,
    HEALTH_ISSUE_MARKER_UNREADABLE,
    HEALTH_ISSUE_ROOT_MISSING,
    HEALTH_ISSUE_SAVES_ROOT_MISSING,
)
from .machine import (
    KIND_DIRECTORY,
    KIND_FILE,
    KIND_INACCESSIBLE,
    KIND_MISSING,
    READ_INVALID_TEXT,
    READ_MISSING,
    READ_OK,
    READ_UNREADABLE,
    PathKind,
    ReadStatus,
)
from .placement import (
    CAVEAT_APP_RELATIVE_PATH_UNEXPANDED,
    CAVEAT_CFG_LINE_DROPPED,
    CAVEAT_CFG_VALUE_REJECTED,
    CAVEAT_CONTENT_DIR_OBSERVATION,
    CAVEAT_CONTENT_PATH_UNNAMED,
    CAVEAT_CORE_GENERATION_MISMATCH,
    CAVEAT_CORE_GENERATION_UNESTABLISHED,
    CAVEAT_CORE_MULTI_OPTION,
    CAVEAT_CORE_MODE_UNESTABLISHED,
    CAVEAT_CORE_OPTION_VALUE_UNESTABLISHED,
    CAVEAT_CORE_SAVESTATES_UNSUPPORTED,
    CAVEAT_OPTION_ENTRY_RETIRED,
    CAVEAT_CORE_SUSPECT,
    CAVEAT_CORE_UNAUDITED,
    CAVEAT_CORE_UNQUERYABLE,
    CAVEAT_DEAD_SYMLINK,
    CAVEAT_EMULATOR_CONFIG_UNREAD,
    CAVEAT_EMULATOR_READ_UNESTABLISHED,
    CAVEAT_FEATURE_SWITCH_ABSENT,
    CAVEAT_FILENAMES_CONTENT_CONDITIONAL,
    CAVEAT_FILENAMES_UNVERIFIED,
    CAVEAT_FILE_NAMES_UNESTABLISHED,
    CAVEAT_FILE_SET_ACROSS_SYSTEMS,
    CAVEAT_FILE_SET_SPANS_ROOTS,
    CAVEAT_INVALID_SAVE_DIRECTORY,
    CAVEAT_INVALID_SCREENSHOT_DIRECTORY,
    CAVEAT_NO_CORE,
    CAVEAT_PATCH_FORMATS_UNESTABLISHED,
    CAVEAT_PER_GAME_ALTERNATIVE_EMULATOR,
    CAVEAT_PER_GAME_BUILD_LAYER_UNREAD,
    CAVEAT_PER_GAME_LAYER_UNREAD,
    CAVEAT_PER_GAME_OVERRIDE,
    CAVEAT_PER_GAME_OVERRIDES_PRESENT,
    CAVEAT_SANDBOX_PATH_UNTRANSLATED,
    CAVEAT_SAVE_DIR_LAUNCH_DEPENDENT,
    CAVEAT_SAVE_INSIDE_CONTENT,
    CAVEAT_SAVE_INSIDE_IMAGE,
    CAVEAT_SAVESTATE_INSIDE_IMAGE,
    CAVEAT_SAVESTATE_SUPPORT_MACHINE_DEPENDENT,
    CAVEAT_SAVE_ROOT_REDIRECTED,
    CAVEAT_SAVE_ROOT_REVOKED,
    CAVEAT_SAVE_ROOT_UNRESOLVABLE,
    CAVEAT_SAVE_WRITES_DISCARDED,
    CAVEAT_SAVE_DIR_UNLISTABLE,
    CAVEAT_SOFT_PATCHING_APPLIES,
    CAVEAT_SORTED_DIR_MISSING,
    CAVEAT_SORTED_DIR_UNCREATABLE,
    CAVEAT_SYMLINK_LOOP,
    CAVEAT_SYSTEM_DIRECTORY_CLEARED,
    CAVEAT_UNKNOWN_OPTION_VALUE,
    CAVEAT_CORE_OWN_WRITES_UNESTABLISHED,
    CAVEAT_UNVERIFIED_VERSION,
    FILE_SET_DECLARED,
    FILE_SET_OBSERVED,
    FILE_SET_UNKNOWN,
    GRANULARITIES,
    GRANULARITY_NONE,
    GRANULARITY_PER_GAME_FILE,
    GRANULARITY_PER_GAME_DIRECTORY,
    GRANULARITY_PER_GAME_FILES,
    GRANULARITY_SHARED_CARD,
    GRANULARITY_SHARED_FILE,
    HOLE_CONTENT_DIR,
    HOLE_CONTENT_DIR_NAME,
    HOLE_CWD,
    HOLE_LIBRARY_NAME,
    HOLE_REGION,
    HOLE_ROM_STEM,
    HOLE_SAVE_ID,
    KEYINGS,
    KEYING_GAME_ID,
    KEYING_PACK,
    KEYING_ROM_NAME,
    KEYING_TITLE,
    KEYING_SERIAL,
    KEYING_TITLE_ID,
    PATCH_CONTINUATION_INDICES,
    PATCH_FORMATS,
    PATCH_FORMAT_BPS,
    PATCH_FORMAT_IPS,
    PATCH_FORMAT_UPS,
    PATCH_FORMAT_XDELTA,
    CORE_MODE_UNESTABLISHED_REASONS,
    EMULATOR_CONFIG_UNREADABLE_REASONS,
    ENUMERATED_DATA,
    ESTABLISHED_FOR_CONSOLE,
    ESTABLISHED_FOR_DEFAULT_SAVE_NAME,
    ESTABLISHED_FOR_DRIVER_NAMED_CONTENT,
    ESTABLISHED_FOR_MENU_SLOT_SAVES,
    ESTABLISHED_FOR_RAW_CARTRIDGE_IMAGE,
    ESTABLISHED_FOR_SINGLE_DISK_IMAGE,
    ESTABLISHED_FOR_UNPACKED_GAME_DIRECTORY,
    FILES_ESTABLISHED_FOR_TOKENS,
    REASON_ACTIVE_USER_UNRECORDED,
    REASON_CARD_INDEX_OUTSIDE_RECORDED_NAMES,
    REASON_CONFIGURED_USER_HAS_NO_TREE,
    REASON_CONFIGURED_USER_ID_UNREAD,
    REASON_CONFIGURED_USER_TREE_NAMED,
    REASON_CONFIGURED_USER_NOT_SET_UP,
    REASON_CONFIGURED_USER_SETUP_UNESTABLISHED,
    REASON_CONTENT_CLASS_UNNAMED,
    REASON_CONTENT_CLASS_UNRECORDED,
    REASON_DATA_ROOT_DECIDED_BY_LAUNCH,
    REASON_EMULATED_MODEL_UNRECORDED,
    REASON_HDD_PATH_UNSET,
    REASON_INI_OUTRANKED_BY_CASCADE,
    REASON_INI_PRESENCE_UNESTABLISHED,
    REASON_INI_SEARCH_PATH_UNLISTABLE,
    REASON_KEY_UNREAD,
    REASON_LISTED_USER_ACCOUNT_UNESTABLISHED,
    REASON_MLC_LAUNCH_FLAG_OUTRANKS_CONFIG,
    REASON_NO_LISTED_USER_ACCOUNT,
    REASON_NO_USER_DIRECTORY,
    REASON_NO_USER_PRESELECTED,
    REASON_REGION_DECIDED_BY_DISC,
    REASON_SAVEPATH_CONFIG_UNREADABLE,
    REASON_SAVEPATH_UNTRANSLATABLE,
    REASON_SESSION_OVERRIDE_SET,
    REASON_SLOT_DEVICE_UNINTERPRETED,
    REASON_SLOT_HOLDS_AGP_DEVICE,
    REASON_USER_LISTING_UNESTABLISHED,
    REASON_VIRTUAL_SD_DISABLED,
    ROLE_BATTERY,
    ROLE_NOTES,
    ROLE_DISK_DIFF,
    ROLE_HIGH_SCORE,
    ROLE_MEMORY_CARD,
    ROLE_SETTINGS,
    ROLES,
    ROOT_CONTENT_DIRECTORY,
    ROOT_EMULATOR_DIRECTORY,
    ROOT_KINDS,
    ROOT_SAVEFILE_DIRECTORY,
    ROOT_SAVESTATE_DIRECTORY,
    ROOT_SYSTEM_DIRECTORY,
    ROOT_WORKING_DIRECTORY,
    STATE_ROOT_CONTENT_DIRECTORY,
    STATE_ROOT_EMULATOR_DIRECTORY,
    STATE_ROOT_WORKING_DIRECTORY,
    SCREENSHOT_ROOT_KINDS,
    SCREENSHOT_ROOT_DIRECTORY,
    SCREENSHOT_ROOT_CONTENT_DIRECTORY,
    STATE_ROOT_KINDS,
    UNRESOLVED_CORE_NOT_INSTALLED,
    UNRESOLVED_EMULATOR_CONFIG_PATH_UNTRANSLATABLE,
    UNRESOLVED_EMULATOR_CONFIG_UNREADABLE,
    UNRESOLVED_MOD_WIRING_UNESTABLISHED,
    UNRESOLVED_STANDALONE,
    UNRESOLVED_STANDALONE_VARIANT_UNESTABLISHED,
    UNRESOLVED_TEXTURE_WIRING_UNESTABLISHED,
    FileSetState,
    Keying,
    PatchFormat,
    RootKind,
    StateRootKind,
)

__all__ = [
    # The package's own version — pyproject's second spelling (see the top of
    # this module)
    "__version__",
    # Entry points
    "detect",
    "every_installation",
    # The one capability a host grants: which zstd provider opens an AppImage
    "register_zstd_provider",
    "zstd_provider",
    "ZstdProvider",
    # The vocabulary the questions take, and how to check a name against it
    "from_esde_system",
    "known_systems",
    "vocabulary_platform_tags",
    # Platform translation — the crosswalk half (atlas.platforms)
    "KNOWN_PLATFORM_VOCABULARIES",
    "IgdbIdentity",
    "PlatformIdentities",
    "known_platforms",
    "load_platform_crosswalk",
    "platform_identities",
    "platforms_for",
    # The aggregate over detect
    "EveryInstallation",
    "InstallationAnswer",
    # Handles: what detect answers with, and what every question is asked of
    "Installation",
    "RetroDeck",
    "EmuDeck",
    "BareRetroArchFlatpak",
    "BareRetroArchNative",
    # Answers
    "SavefilePlacement",
    "SavestateAbsence",
    "SavestatePlacement",
    "ScreenshotPlacement",
    "TexturePlacement",
    "ModPlacement",
    "ModTree",
    "SoftPatchAnswer",
    "SoftPatchCandidate",
    "Unresolved",
    "FileSet",
    "FileGroup",
    "Granularity",
    "ModeAlternative",
    "OptionReading",
    "Health",
    "CatalogueAnswer",
    "SystemsAnswer",
    "PlatformSystemsAnswer",
    "PlatformSystemMatch",
    "SystemPlatformsAnswer",
    "PLATFORM_STATUS_DECLARED",
    "PLATFORM_STATUS_DISABLED",
    "PLATFORM_STATUS_ABSENT",
    "PLATFORM_TAGS_CATALOGUE",
    "PLATFORM_TAGS_VOCABULARY",
    "CAVEAT_PLATFORM_UNMAPPED",
    "CAVEAT_PLATFORM_UNKNOWN",
    "CAVEAT_PLATFORM_SCRAPING_IGNORED",
    "LaunchabilityAnswer",
    "LAUNCH_VERDICTS",
    "VERDICT_LAUNCHABLE",
    "VERDICT_NOT_ACCEPTED",
    "VERDICT_ENTRY_NOT_ACCEPTED",
    "VERDICT_NEEDS_INSTALLATION",
    "VERDICT_UNKNOWN",
    "CAVEAT_ENTRY_FORMAT_UNCLAIMED",
    "CAVEAT_ARCHIVE_CONTENTS_UNREAD",
    "CAVEAT_ENTRY_FORMAT_UNESTABLISHED",
    "InstallFirstFormat",
    "StandaloneLaunchCard",
    "load_launch_formats",
    "load_standalone_launch",
    "lookup_install_first",
    "lookup_standalone_launch",
    "esde_extension",
    "RomPlacement",
    "EmulatorEntry",
    "FirmwareAnswer",
    "CoreFirmware",
    "FirmwareRequirement",
    "FirmwareAlternatives",
    "FirmwareIdentification",
    "FirmwareIdentity",
    "SuppliedBy",
    "UnclaimedFile",
    "RefusedDeclaration",
    "Caveat",
    # Serializers — one per answer type, the same code the vectors assert
    "savefile_answer_contract",
    "savefile_placement_contract",
    "savestate_absence_contract",
    "savestate_answer_contract",
    "savestate_placement_contract",
    "texture_answer_contract",
    "texture_placement_contract",
    "mod_answer_contract",
    "mod_placement_contract",
    "soft_patch_answer_contract",
    "soft_patch_contract",
    "unresolved_contract",
    "health_contract",
    "installation_contract",
    "installation_answers_contract",
    "catalogue_contract",
    "rom_placement_contract",
    "emulator_contract",
    "systems_contract",
    "platform_systems_contract",
    "system_platforms_contract",
    "launchable_contract",
    "firmware_contract",
    "identification_contract",
    # Vocabulary types
    "PathKind",
    "ReadStatus",
    "RootKind",
    "StateRootKind",
    "FileSetState",
    "Keying",
    "PatchFormat",
    "FirmwareNeed",
    "FirmwareChecked",
    "DeclaredKind",
    "FirmwareIdentityKind",
    "ArchiveReason",
    "CoreDeclarationState",
    "SystemSource",
    # Vocabulary values — path kinds and read statuses (answers carry both)
    "KIND_FILE",
    "KIND_DIRECTORY",
    "KIND_MISSING",
    "KIND_INACCESSIBLE",
    "READ_OK",
    "READ_MISSING",
    "READ_UNREADABLE",
    "READ_INVALID_TEXT",
    # Vocabulary values — emulator kinds, save roots, firmware axes
    "KIND_LIBRETRO",
    "KIND_STANDALONE",
    "ROOT_SAVEFILE_DIRECTORY",
    "ROOT_CONTENT_DIRECTORY",
    "ROOT_SYSTEM_DIRECTORY",
    "ROOT_WORKING_DIRECTORY",
    "ROOT_EMULATOR_DIRECTORY",
    "ROOT_SAVESTATE_DIRECTORY",
    "STATE_ROOT_CONTENT_DIRECTORY",
    "STATE_ROOT_EMULATOR_DIRECTORY",
    "STATE_ROOT_WORKING_DIRECTORY",
    "FILE_SET_OBSERVED",
    "FILE_SET_DECLARED",
    "FILE_SET_UNKNOWN",
    "NEED_REQUIRED",
    "NEED_OPTIONAL",
    "DECLARED_FILE",
    "DECLARED_DIRECTORY",
    "CHECKED_VERIFIED",
    "CHECKED_MISMATCH",
    "CHECKED_UNCHECKED",
    "CHECKED_UNKNOWN",
    "CHECKED_NOT_COMPARABLE",
    "IDENTITY_FILE",
    "IDENTITY_ARCHIVE",
    "ARCHIVE_ROMSET",
    "ARCHIVE_CORE_BUNDLED",
    "DECLARATION_READ",
    "DECLARATION_UNREADABLE",
    "DECLARATION_ABSENT",
    "DECLARATION_PACKAGED",
    "DECLARATION_UNSUPPORTED",
    "SOURCE_OVERRIDE",
    "SOURCE_SYSTEMNAME",
    "SOURCE_SLUG",
    "SOURCE_NONE",
    "SOURCE_CARD",
    "SYSTEMS_WITHOUT_CATALOGUE_ID",
    # Vocabulary values — the holes a caller fills, and the closed sets the
    # contract serializes them beside. A client branches on `needs` and reads
    # `granularity.value` / `root_kind`, so by the tiering rule (a name a client
    # acts on lives in `atlas`) their vocabularies are consumer surface too;
    # without them the only way to branch was a hardcoded string.
    # `ENUMERATED_DATA` is not one of those tuples but the map from a
    # `(code, key)` to the tuple its value is refused against — the registry the
    # caveat constructors check. It is exported for the same reason: a client
    # that wants to know which values a key can take reads the same mapping the
    # constructor enforces, rather than a list copied out of the guide.
    "CORE_MODE_UNESTABLISHED_REASONS",
    "EMULATOR_CONFIG_UNREADABLE_REASONS",
    "ENUMERATED_DATA",
    "ESTABLISHED_FOR_CONSOLE",
    "ESTABLISHED_FOR_DEFAULT_SAVE_NAME",
    "ESTABLISHED_FOR_DRIVER_NAMED_CONTENT",
    "ESTABLISHED_FOR_MENU_SLOT_SAVES",
    "ESTABLISHED_FOR_RAW_CARTRIDGE_IMAGE",
    "ESTABLISHED_FOR_SINGLE_DISK_IMAGE",
    "ESTABLISHED_FOR_UNPACKED_GAME_DIRECTORY",
    "FILES_ESTABLISHED_FOR_TOKENS",
    "REASON_ACTIVE_USER_UNRECORDED",
    "REASON_CARD_INDEX_OUTSIDE_RECORDED_NAMES",
    "REASON_CONFIGURED_USER_HAS_NO_TREE",
    "REASON_CONFIGURED_USER_ID_UNREAD",
    "REASON_CONFIGURED_USER_TREE_NAMED",
    "REASON_CONFIGURED_USER_NOT_SET_UP",
    "REASON_CONFIGURED_USER_SETUP_UNESTABLISHED",
    "REASON_CONTENT_CLASS_UNNAMED",
    "REASON_CONTENT_CLASS_UNRECORDED",
    "REASON_DATA_ROOT_DECIDED_BY_LAUNCH",
    "REASON_EMULATED_MODEL_UNRECORDED",
    "REASON_HDD_PATH_UNSET",
    "REASON_INI_OUTRANKED_BY_CASCADE",
    "REASON_INI_PRESENCE_UNESTABLISHED",
    "REASON_INI_SEARCH_PATH_UNLISTABLE",
    "REASON_KEY_UNREAD",
    "REASON_LISTED_USER_ACCOUNT_UNESTABLISHED",
    "REASON_MLC_LAUNCH_FLAG_OUTRANKS_CONFIG",
    "REASON_NO_LISTED_USER_ACCOUNT",
    "REASON_NO_USER_DIRECTORY",
    "REASON_NO_USER_PRESELECTED",
    "REASON_REGION_DECIDED_BY_DISC",
    "REASON_SAVEPATH_CONFIG_UNREADABLE",
    "REASON_SAVEPATH_UNTRANSLATABLE",
    "REASON_SESSION_OVERRIDE_SET",
    "REASON_SLOT_DEVICE_UNINTERPRETED",
    "REASON_SLOT_HOLDS_AGP_DEVICE",
    "REASON_USER_LISTING_UNESTABLISHED",
    "REASON_VIRTUAL_SD_DISABLED",
    "CFG_LAYER_CONTENT_DIR_OVERRIDE",
    "CFG_LAYER_CORE_OVERRIDE",
    "CFG_LAYER_GAME_OVERRIDE",
    "CFG_LAYER_GLOBAL",
    "CFG_LAYER_KINDS",
    "HOLE_CONTENT_DIR",
    "HOLE_CONTENT_DIR_NAME",
    "HOLE_CWD",
    "HOLE_LIBRARY_NAME",
    "HOLE_REGION",
    "HOLE_ROM_STEM",
    "HOLE_SAVE_ID",
    "GRANULARITY_SHARED_CARD",
    "GRANULARITY_SHARED_FILE",
    "GRANULARITY_NONE",
    "GRANULARITY_PER_GAME_FILE",
    "GRANULARITY_PER_GAME_DIRECTORY",
    "GRANULARITY_PER_GAME_FILES",
    "GRANULARITIES",
    "ROLE_BATTERY",
    "ROLE_NOTES",
    "ROLE_MEMORY_CARD",
    "ROLE_DISK_DIFF",
    "ROLE_HIGH_SCORE",
    "ROLE_SETTINGS",
    "ROLES",
    "KEYING_GAME_ID",
    "KEYING_SERIAL",
    "KEYING_TITLE_ID",
    "KEYING_ROM_NAME",
    "KEYING_TITLE",
    "KEYING_PACK",
    "KEYINGS",
    "PATCH_FORMAT_IPS",
    "PATCH_FORMAT_BPS",
    "PATCH_FORMAT_UPS",
    "PATCH_FORMAT_XDELTA",
    "PATCH_FORMATS",
    "PATCH_CONTINUATION_INDICES",
    "ROOT_KINDS",
    "SCREENSHOT_ROOT_KINDS",
    "SCREENSHOT_ROOT_DIRECTORY",
    "SCREENSHOT_ROOT_CONTENT_DIRECTORY",
    "STATE_ROOT_KINDS",
    # Health finding codes
    "HEALTH_ISSUE_MARKER_MISSING",
    "HEALTH_ISSUE_MARKER_UNREADABLE",
    "HEALTH_ISSUE_MARKER_INVALID",
    "HEALTH_ISSUE_ROOT_MISSING",
    "HEALTH_ISSUE_SAVES_ROOT_MISSING",
    "HEALTH_ISSUE_CONFIG_UNREADABLE",
    "HEALTH_ISSUE_CATALOGUE_INVALID",
    "HEALTH_ISSUE_COMPANION_CONFIG_MISSING",
    "HEALTH_ISSUE_CONTENT_TREE_UNWIRED",
    # Content-tree wiring (the dir_prep pairs behind that finding)
    "ArrangementWiring",
    "WiringRow",
    "load_content_tree_wiring",
    "lookup_content_tree_wiring",
    # Distribution-supplied firmware (which files RetroDECK places itself)
    "DistributionSupplied",
    "SuppliedEntry",
    "load_distribution_supplied",
    "lookup_distribution_supplied",
    # How a distribution spells its own name (presentation, never a key)
    "DistributionLabel",
    "distribution_label",
    "load_distribution_labels",
    # Typed outcome codes
    "UNRESOLVED_CORE_NOT_INSTALLED",
    "UNRESOLVED_STANDALONE",
    "UNRESOLVED_STANDALONE_VARIANT_UNESTABLISHED",
    "UNRESOLVED_EMULATOR_CONFIG_PATH_UNTRANSLATABLE",
    "UNRESOLVED_EMULATOR_CONFIG_UNREADABLE",
    "UNRESOLVED_TEXTURE_WIRING_UNESTABLISHED",
    "UNRESOLVED_MOD_WIRING_UNESTABLISHED",
    # Caveat codes
    "CAVEAT_APP_RELATIVE_PATH_UNEXPANDED",
    "CAVEAT_ARRANGEMENT_UNVERIFIED",
    "CAVEAT_ARRANGEMENT_VERSION_DRIFTED",
    "CAVEAT_CFG_LINE_DROPPED",
    "CAVEAT_CFG_VALUE_REJECTED",
    "CAVEAT_CONFIG_HOME_RELOCATED",
    "CAVEAT_CONTENT_DIR_OBSERVATION",
    "CAVEAT_CONTENT_PATH_UNNAMED",
    "CAVEAT_CORE_DIR_UNRESOLVED",
    "CAVEAT_CORE_ENUMERATION_INCOMPLETE",
    "CAVEAT_CORE_GENERATION_MISMATCH",
    "CAVEAT_CORE_GENERATION_UNESTABLISHED",
    "CAVEAT_CORE_INFO_UNREADABLE",
    "CAVEAT_CORE_MULTI_OPTION",
    "CAVEAT_CORE_NOT_INSTALLED",
    "CAVEAT_CORE_MODE_UNESTABLISHED",
    "CAVEAT_CORE_OPTION_VALUE_UNESTABLISHED",
    "CAVEAT_CORE_SAVESTATES_UNSUPPORTED",
    "CAVEAT_OPTION_ENTRY_RETIRED",
    "CAVEAT_CORE_SUSPECT",
    "CAVEAT_CORE_UNAUDITED",
    "CAVEAT_CORE_UNQUERYABLE",
    "CAVEAT_CORE_WITHOUT_SYSTEMNAME",
    "CAVEAT_DEAD_SYMLINK",
    "CAVEAT_EMULATOR_CATALOGUE_EXCLUSIVE",
    "CAVEAT_EMULATOR_CATALOGUE_SEALED",
    "CAVEAT_EMULATOR_LIST_DERIVED",
    "CAVEAT_EMULATOR_CATALOGUE_UNAVAILABLE",
    "CAVEAT_EMULATOR_CATALOGUE_UNESTABLISHED",
    "CAVEAT_EMULATOR_CATALOGUE_UNREADABLE",
    "CAVEAT_EMULATOR_CONFIG_UNREAD",
    "CAVEAT_EMULATOR_READ_UNESTABLISHED",
    "CAVEAT_FEATURE_SWITCH_ABSENT",
    "CAVEAT_FILENAMES_CONTENT_CONDITIONAL",
    "CAVEAT_FILENAMES_UNVERIFIED",
    "CAVEAT_FILE_NAMES_UNESTABLISHED",
    "CAVEAT_FILE_SET_ACROSS_SYSTEMS",
    "CAVEAT_FILE_SET_SPANS_ROOTS",
    "CAVEAT_EMULATOR_CONFIG_UNREADABLE",
    "CAVEAT_FIRMWARE_BUILTIN_REPLACEMENT",
    "CAVEAT_FIRMWARE_CONTENT_CONTRADICTORY",
    "CAVEAT_FIRMWARE_CONTENT_UNIDENTIFIED",
    "CAVEAT_FIRMWARE_CONTENT_UNSTATED",
    "CAVEAT_FIRMWARE_IMAGE_AMBIGUOUS",
    "CAVEAT_FIRMWARE_IMAGE_CONTRADICTED",
    "CAVEAT_FIRMWARE_IMAGE_IDENTIFIED",
    "CAVEAT_FIRMWARE_IMAGE_UNLISTED",
    "CAVEAT_FIRMWARE_DECLARATION_UNKNOWN",
    "CAVEAT_FIRMWARE_PACKAGED_DECLARATION",
    "CAVEAT_FIRMWARE_DECLARATION_UNREAD",
    "CAVEAT_FIRMWARE_DIRECTORY_HOLDS_NO_CANDIDATE",
    "CAVEAT_FIRMWARE_DIRECTORY_HOLDS_NO_IMAGE",
    "CAVEAT_FIRMWARE_PATH_ESCAPES_ROOT",
    "CAVEAT_FIRMWARE_PATH_INACCESSIBLE",
    "CAVEAT_FIRMWARE_PATH_LAUNCH_DEPENDENT",
    "CAVEAT_FIRMWARE_PATH_NAMES_NO_FILE",
    "CAVEAT_FIRMWARE_PATH_NOT_A_DIRECTORY",
    "CAVEAT_FIRMWARE_PATH_OBSTRUCTED",
    "CAVEAT_FIRMWARE_PATH_UNRESOLVABLE",
    "CAVEAT_FIRMWARE_ROOT_MISSING",
    "CAVEAT_FIRMWARE_ROOT_UNUSABLE",
    "CAVEAT_FIRMWARE_SCAN_INCOMPLETE",
    "CAVEAT_FIRMWARE_SEARCH_UNVERIFIED",
    "CAVEAT_FIRMWARE_SUPPLIED_SOURCE_UNREADABLE",
    "CAVEAT_FIRMWARE_UNREADABLE",
    "CAVEAT_FIRMWARE_IDENTITY_NOT_COMPARABLE",
    "CAVEAT_FRONTEND_MARKER_MISMATCH",
    "CAVEAT_FRONTEND_SETTINGS_UNREADABLE",
    "CAVEAT_INFO_PATH_UNRESOLVED",
    "CAVEAT_INVALID_SAVE_DIRECTORY",
    "CAVEAT_INVALID_SCREENSHOT_DIRECTORY",
    "CAVEAT_NO_CORE",
    "CAVEAT_NO_FIRMWARE_DECLARATION",
    "CAVEAT_NO_FIRMWARE_REQUIREMENT",
    "CAVEAT_PATCH_FORMATS_UNESTABLISHED",
    "CAVEAT_PER_GAME_ALTERNATIVE_EMULATOR",
    "CAVEAT_PER_GAME_BUILD_LAYER_UNREAD",
    "CAVEAT_PER_GAME_LAYER_UNREAD",
    "CAVEAT_PER_GAME_OVERRIDE",
    "CAVEAT_PER_GAME_OVERRIDES_PRESENT",
    "CAVEAT_ROM_PATH_UNDECLARED",
    "CAVEAT_ROM_PATH_UNRESOLVED",
    "CAVEAT_SANDBOX_PATH_UNTRANSLATED",
    "CAVEAT_SAVE_DIR_LAUNCH_DEPENDENT",
    "CAVEAT_SAVE_INSIDE_CONTENT",
    "CAVEAT_SAVE_INSIDE_IMAGE",
    "CAVEAT_SAVESTATE_INSIDE_IMAGE",
    "CAVEAT_SAVESTATE_SUPPORT_MACHINE_DEPENDENT",
    "CAVEAT_SAVE_ROOT_REDIRECTED",
    "CAVEAT_SAVE_ROOT_REVOKED",
    "CAVEAT_SAVE_ROOT_UNRESOLVABLE",
    "CAVEAT_SAVE_WRITES_DISCARDED",
    "CAVEAT_SAVE_DIR_UNLISTABLE",
    "CAVEAT_SOFT_PATCHING_APPLIES",
    "CAVEAT_SORTED_DIR_MISSING",
    "CAVEAT_SORTED_DIR_UNCREATABLE",
    "CAVEAT_STANDALONE_UNSUPPORTED",
    "CAVEAT_SYMLINK_LOOP",
    "CAVEAT_SYSTEM_ASSIGNMENT_DERIVED",
    "CAVEAT_SYSTEM_NOT_IN_CATALOGUE",
    "CAVEAT_SYSTEM_ASSIGNMENT_MAY_HIDE_CORES",
    "CAVEAT_SYSTEM_DIRECTORY_CLEARED",
    "CAVEAT_SYSTEM_UNKNOWN",
    "CAVEAT_UNKNOWN_OPTION_VALUE",
    "CAVEAT_UNVERIFIED_VERSION",
    "CAVEAT_CORE_OWN_WRITES_UNESTABLISHED",
]
