#!/usr/bin/env python3
"""The mark as terminal text: a half-block icon, and an ASCII drawing behind it.

`install.sh` is the first thing a user of this program sees, and it draws the
mark before it does anything. It cannot render an image and it must not grow a
dependency to do it, so the art is TEXT embedded in the script — and text
embedded in a script is the kind of thing that gets hand-tidied until it no
longer resembles what it is a picture of. `scripts/check_generated_installer_logo.py`
regenerates it and fails on any difference.

**The icon is half-blocks, and the colours ARE the picture.** Every cell is one
``▀`` whose foreground is the pixel above and whose background is the pixel
below, so a text row carries two rows of pixels and a cell carries two colours.
That is the whole technique: nothing is drawn in glyph SHAPES, which is why
there is no half-block icon at all where colour is off — a page of ``▀`` in one
colour is not a mark, it is a grey slab.

**It is the real mark, not a silhouette of it** — the disc with its facet, the
navy ring, the tan and peach buttons — drawn by `gen.standalone` and rasterised
by `rsvg-convert`.

**The pose is the tab glyph's.** `arc_rot` turns the sync ring to follow the
disc's facet; at this size that lands the ring's two gaps off the horizontal,
where a gap half a cell high reads as a lopsided ring rather than as a turn.
`tabicon.STRIP_GEOMETRY` zeroes it for the same reason, and thickens the ring
stroke for the same reason again — at 28 columns the mark's own stroke is the
thinnest thing on screen.

**One assumption, stated once:** the terminal's background is dark. The mark's
antialiased edge is blended onto :data:`TERMINAL_BG` because a half-transparent
pixel has to be given SOME colour, and on the reference machine the terminal is
Konsole or wezterm with a dark ground. A pixel still under :data:`ALPHA_FLOOR`
after that is drawn with the terminal's own background instead, so the fringe
does not paint near-black boxes on a terminal whose dark is a different dark.

The ASCII drawing behind it is a different technique for a different question:
it is CLASS-drawn, not sampled, because without colour the only thing left to
carry the mark is glyph weight. The ring, the body and the buttons are rendered
as separate layers and each cell takes the character its heaviest layer earns.

Everything here decodes its own PNG and does its own resampling: this module and
its check have to run wherever the repository's lint runs, which is a Python and
`rsvg-convert` and nothing else.
"""

from __future__ import annotations

import dataclasses
import functools
import math
import pathlib
import struct
import subprocess
import sys
import zlib

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent

# What the mark is rasterised at before it is sampled. The drawing is a
# 200-unit square, so an icon cell is about 36 source pixels on a side — enough
# that its colour is an average rather than a sample.
RENDER_SIZE = 1024

# How wide the icon is, and how wide a terminal cell is against its height. The
# ratio is what decides the number of ROWS: 28 columns of a cell 0.45 as wide as
# it is tall is 12.6 rows of drawing, which is 13 rows of text.
ICON_COLUMNS = 28
CELL_ASPECT = 14.4 / 32.0

# The ground the mark's antialiased edge is blended onto, and the alpha below
# which a pixel is left to the terminal instead.
TERMINAL_BG = (0x1E, 0x1F, 0x2E)
ALPHA_FLOOR = 0.5

# The ring stroke at icon size, as a multiple of the mark's own. The strip glyph
# scales it by the same amount and for the same reason.
RING_STROKE = 1.3

# The ASCII drawing: its width, and how many samples a cell is judged over. A
# cell is SUB across and 2*SUB down, because a cell is about twice as tall as it
# is wide.
ASCII_COLUMNS = 28
ASCII_SUB = 4
# Alpha above which a sub-sample counts as covered by a layer.
ASCII_COVERED = 110 / 255
# The button radius at this size. Below the mark's own, because a button drawn
# at full radius closes the gap to the ring and the two read as one shape.
ASCII_DOT_SCALE = 0.8

# The wordmark, which nothing reads yet. Its height is CHOSEN, not derived: the
# letterforms' own aspect asks for five rows at this width, and the slab face
# needs the sixth to keep its serifs.
WORDMARK_COLUMNS = 79
WORDMARK_ROWS = 6

_MARKERS = (
    "# >>> generated by scripts/logo/terminal.py — do not edit",
    "# <<< generated",
)


# --------------------------------------------------------------------------- #
# Reading a PNG                                                               #
# --------------------------------------------------------------------------- #
class Image:
    """An 8-bit RGBA raster, addressed by pixel."""

    def __init__(self, width: int, height: int, pixels: bytes) -> None:
        self.width = width
        self.height = height
        self.pixels = pixels

    def at(self, x: int, y: int) -> tuple[int, int, int, int]:
        start = (y * self.width + x) * 4
        r, g, b, a = self.pixels[start : start + 4]
        return r, g, b, a


def decode_png(data: bytes) -> Image:
    """Decode a non-interlaced 8-bit RGBA PNG.

    Refuses anything else rather than guessing: what this reads is what
    `rsvg-convert` emits, so a different shape means that changed and the reader
    has to be looked at rather than coaxed.
    """
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    width = height = 0
    body = bytearray()
    position = 8
    while position < len(data):
        (length,) = struct.unpack(">I", data[position : position + 4])
        kind = data[position + 4 : position + 8]
        chunk = data[position + 8 : position + 8 + length]
        if kind == b"IHDR":
            width, height, depth, colour, compression, filtering, interlace = struct.unpack(">IIBBBBB", chunk)
            if (depth, colour, compression, filtering, interlace) != (8, 6, 0, 0, 0):
                raise ValueError(f"expected 8-bit RGBA, non-interlaced, got {chunk[8:]!r}")
        elif kind == b"IDAT":
            body += chunk
        elif kind == b"IEND":
            break
        position += 12 + length
    return Image(width, height, _unfilter(zlib.decompress(bytes(body)), width, height))


def _unfilter(raw: bytes, width: int, height: int) -> bytes:
    """Undo PNG's per-scanline filters, answering the pixel bytes.

    Each scanline is preceded by one byte naming its filter, and every filter
    but the first predicts a byte from its neighbours — so this cannot be done
    out of order or in parallel: row N is decoded against the already-decoded
    row N-1.
    """
    stride = width * 4
    out = bytearray(stride * height)
    position = 0
    for y in range(height):
        filter_kind = raw[position]
        position += 1
        line = bytearray(raw[position : position + stride])
        position += stride
        above = out[(y - 1) * stride : y * stride] if y else bytes(stride)
        for x in range(stride):
            left = line[x - 4] if x >= 4 else 0
            up = above[x]
            upper_left = above[x - 4] if x >= 4 else 0
            if filter_kind == 1:
                line[x] = (line[x] + left) & 0xFF
            elif filter_kind == 2:
                line[x] = (line[x] + up) & 0xFF
            elif filter_kind == 3:
                line[x] = (line[x] + (left + up) // 2) & 0xFF
            elif filter_kind == 4:
                line[x] = (line[x] + _paeth(left, up, upper_left)) & 0xFF
            elif filter_kind != 0:
                raise ValueError(f"unknown PNG filter {filter_kind} on row {y}")
        out[y * stride : (y + 1) * stride] = line
    return bytes(out)


def _paeth(left: int, up: int, upper_left: int) -> int:
    estimate = left + up - upper_left
    da, db, dc = abs(estimate - left), abs(estimate - up), abs(estimate - upper_left)
    if da <= db and da <= dc:
        return left
    return up if db <= dc else upper_left


# --------------------------------------------------------------------------- #
# Drawing and sampling                                                        #
# --------------------------------------------------------------------------- #
def terminal_pose() -> object:
    """The geometry the terminal renderings are drawn in: the tab glyph's."""
    import gen  # noqa: PLC0415 — a sibling module, resolved through the path build.py sets

    default = gen.DEFAULT_GEOMETRY
    return dataclasses.replace(
        default,
        arc_rot=0.0,
        arc_w=default.arc_w * RING_STROKE,
        arrow_len=default.arrow_len * RING_STROKE,
        arrow_half=default.arrow_half * RING_STROKE,
        arrow_round=default.arrow_round * RING_STROKE,
    )


def rasterise(svg: str, size: int = RENDER_SIZE) -> Image:
    """Hand an SVG to `rsvg-convert` and read the PNG back."""
    rendered = subprocess.run(
        ["rsvg-convert", "-f", "png", "-w", str(size), "-h", str(size)],
        input=svg.encode("utf-8"),
        capture_output=True,
        check=True,
    ).stdout
    return decode_png(rendered)


Sample = tuple[float, float, float, float]  # r, g, b as 0-255; a as 0-1


def box_sample(image: Image, box: tuple[float, float, float, float], across: int, down: int) -> list[list[Sample]]:
    """Area-average *box* of *image* down to *across* x *down* samples.

    A box filter rather than a fancier kernel, and over PREMULTIPLIED alpha. The
    premultiplication is the part that matters: averaging colour and alpha apart
    lets a transparent pixel's colour — which is arbitrary, and in a rasteriser's
    output is usually black — pull the average of its opaque neighbours towards
    itself, and the mark grows a dark fringe that nothing in the drawing put
    there.

    *box* may reach outside the image; what lies outside is transparent, which
    is how the grid gets rows the drawing does not fill.
    """
    left, top, right, bottom = box
    step_x = (right - left) / across
    step_y = (bottom - top) / down
    rows = []
    for row in range(down):
        y0, y1 = top + row * step_y, top + (row + 1) * step_y
        line = []
        for column in range(across):
            x0, x1 = left + column * step_x, left + (column + 1) * step_x
            red = green = blue = alpha = weight = 0.0
            for y in range(math.floor(y0), math.ceil(y1)):
                overlap_y = min(y + 1.0, y1) - max(float(y), y0)
                if overlap_y <= 0 or not 0 <= y < image.height:
                    weight += max(0.0, overlap_y) * (x1 - x0)
                    continue
                for x in range(math.floor(x0), math.ceil(x1)):
                    overlap_x = min(x + 1.0, x1) - max(float(x), x0)
                    if overlap_x <= 0:
                        continue
                    area = overlap_x * overlap_y
                    weight += area
                    if not 0 <= x < image.width:
                        continue
                    r, g, b, a = image.at(x, y)
                    scaled = area * a / 255
                    red += r * scaled
                    green += g * scaled
                    blue += b * scaled
                    alpha += scaled
            if alpha > 0:
                line.append((red / alpha, green / alpha, blue / alpha, alpha / weight if weight else 0.0))
            else:
                line.append((0.0, 0.0, 0.0, 0.0))
        rows.append(line)
    return rows


Pixel = tuple[int, int, int] | None  # None: leave it to the terminal


def composite(samples: list[list[Sample]]) -> list[list[Pixel]]:
    """Blend onto the assumed ground, and drop what is still barely there."""
    out = []
    for line in samples:
        row = []
        for red, green, blue, alpha in line:
            if alpha < ALPHA_FLOOR:
                row.append(None)
                continue
            mix = alpha
            row.append(
                (
                    round(red * mix + TERMINAL_BG[0] * (1 - mix)),
                    round(green * mix + TERMINAL_BG[1] * (1 - mix)),
                    round(blue * mix + TERMINAL_BG[2] * (1 - mix)),
                )
            )
        out.append(row)
    return out


# --------------------------------------------------------------------------- #
# The icon                                                                    #
# --------------------------------------------------------------------------- #
Cell = tuple[str, Pixel, Pixel]  # character, foreground, background

UPPER_HALF = "▀"
LOWER_HALF = "▄"


def half_block_cells(pixels: list[list[Pixel]]) -> list[list[Cell]]:
    """Pair the pixel rows up into cells of one block character each.

    Three shapes, and the reason for each: two transparent halves are a SPACE
    with the terminal's own colours, because painting a box the colour of a
    guess at the background is the one thing that looks wrong on the terminal
    the guess was wrong about. One transparent half is the block that fills the
    other. Everything else is ``▀`` with the lower pixel as its background —
    including two halves that happen to be the same colour, which a full block
    would draw identically and which is not worth a fourth shape to notice.
    """
    rows = []
    for row in range(len(pixels) // 2):
        line = []
        for column in range(len(pixels[0])):
            upper, lower = pixels[row * 2][column], pixels[row * 2 + 1][column]
            if upper is None and lower is None:
                line.append((" ", None, None))
            elif lower is None:
                line.append((UPPER_HALF, upper, None))
            elif upper is None:
                line.append((LOWER_HALF, lower, None))
            else:
                line.append((UPPER_HALF, upper, lower))
        rows.append(line)
    return rows


def icon_cells() -> list[list[Cell]]:
    """The mark as half-block cells: the real thing, disc and facet and all."""
    import gen  # noqa: PLC0415 — a sibling module, resolved through the path build.py sets

    image = rasterise(gen.standalone(gen.BY_NAME[gen.CHOSEN], terminal_pose(), RENDER_SIZE))
    rows = icon_rows()
    # The drawing is square and fills its raster. The grid is as wide as the
    # drawing and as tall as thirteen rows of cells are, which is taller — so the
    # box reaches past the top and bottom into transparency, and the icon keeps
    # the mark's own proportions instead of being stretched to fit.
    per_column = image.width / ICON_COLUMNS
    height = rows / CELL_ASPECT * per_column
    middle = image.height / 2
    box = (0.0, middle - height / 2, float(image.width), middle + height / 2)
    return half_block_cells(composite(box_sample(image, box, ICON_COLUMNS, rows * 2)))


def icon_rows() -> int:
    """How many text rows the icon is, from its width and the cell's shape."""
    return math.ceil(ICON_COLUMNS * CELL_ASPECT - 1e-6)


# --------------------------------------------------------------------------- #
# The ASCII drawing                                                           #
# --------------------------------------------------------------------------- #
RING, BUTTON = "r", "b"


def _layer_svg(geometry: object, layer: str) -> str:
    """One part of the mark, drawn in flat black on nothing.

    Black because only the ALPHA is read back: what is wanted is coverage, and
    a layer drawn in its own colour would answer a question about the colour of
    its antialiased edge instead.
    """
    import gen  # noqa: PLC0415 — a sibling module, resolved through the path build.py sets
    import tabicon  # noqa: PLC0415 — likewise; it owns the ring's two paths

    if layer == "ring":
        arc, head = tabicon.ring_arc(geometry)
        one = (
            f'<path d="{arc}" fill="none" stroke="#000" stroke-width="{geometry.arc_w:.2f}" stroke-linecap="round"/>'
            f'<polygon points="{head}" fill="#000" stroke="#000" '
            f'stroke-width="{geometry.arrow_round:.2f}" stroke-linejoin="round"/>'
        )
        inner = f"<g>{one}</g><g transform=\"rotate(180 {gen.CX:.0f} {gen.CY:.0f})\">{one}</g>"
    else:
        inner = "".join(f'<path d="{d}" fill="#000"/>' for d in gen.arm_paths(geometry, 0.0) if d)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {gen.VIEW:.0f} {gen.VIEW:.0f}" '
        f'width="{RENDER_SIZE}" height="{RENDER_SIZE}">{inner}</svg>'
    )


def ascii_cells() -> list[list[tuple[str, str]]]:
    """The ASCII drawing as rows of ``(character, colour class)``.

    CLASS-drawn rather than sampled: each layer is rendered on its own and a
    cell takes the character its heaviest layer earns, so the ring stays a ring
    at the width of a single character. A cell sampled from the finished mark
    would average ring and disc together and answer with the weight of neither.

    The buttons are not rendered at all — they are circles, and a circle is
    cheaper and rounder to test for than to rasterise and measure.
    """
    import gen  # noqa: PLC0415 — a sibling module, resolved through the path build.py sets

    geometry = terminal_pose()
    rows = ASCII_COLUMNS // 2
    across, down = ASCII_COLUMNS * ASCII_SUB, rows * 2 * ASCII_SUB
    reach = geometry.arc_r + geometry.arc_w / 2 + 1.5
    scale = across / (2 * reach)
    box = tuple(value / gen.VIEW * RENDER_SIZE for value in (gen.CX - reach, gen.CY - reach, gen.CX + reach, gen.CY + reach))

    def coverage(layer: str) -> list[list[bool]]:
        sampled = box_sample(rasterise(_layer_svg(geometry, layer)), box, across, down)
        return [[alpha >= ASCII_COVERED for _r, _g, _b, alpha in line] for line in sampled]

    ring, body = coverage("ring"), coverage("body")
    buttons = _button_coverage(gen, geometry, across, down, scale)

    out = []
    for row in range(rows):
        line = []
        for column in range(ASCII_COLUMNS):
            cells = [
                (ring[y][x], body[y][x], buttons[y][x])
                for y in range(row * 2 * ASCII_SUB, (row + 1) * 2 * ASCII_SUB)
                for x in range(column * ASCII_SUB, (column + 1) * ASCII_SUB)
            ]
            total = len(cells)
            ring_share = sum(one[0] for one in cells) / total
            body_share = sum(one[1] for one in cells) / total
            button_share = sum(one[2] for one in cells) / total
            if button_share >= 0.45:
                line.append(("O", BUTTON))
            elif ring_share >= 0.55:
                line.append(("#", RING))
            elif ring_share >= 0.25:
                line.append(("+", RING))
            elif body_share >= 0.5:
                line.append((":", RING))
            elif ring_share >= 0.1 or body_share >= 0.2:
                line.append((".", RING))
            else:
                line.append((" ", RING))
        out.append(line)
    return out


def _button_coverage(gen: object, geometry: object, across: int, down: int, scale: float) -> list[list[bool]]:
    """Which sub-samples a button covers, tested rather than drawn."""
    _centre, _span, corners = gen._diamond(geometry, 0.0)
    radius = geometry.dot_r * ASCII_DOT_SCALE * scale
    squash = down / across
    covered = [[False] * across for _ in range(down)]
    for _name, cx, cy, _d in corners:
        x0 = (cx - gen.CX) * scale + across / 2
        y0 = (cy - gen.CY) * scale * squash + down / 2
        for y in range(down):
            for x in range(across):
                if (x + 0.5 - x0) ** 2 + ((y + 0.5 - y0) / squash) ** 2 <= radius * radius:
                    covered[y][x] = True
    return covered


# --------------------------------------------------------------------------- #
# The wordmark, which nothing reads yet                                       #
# --------------------------------------------------------------------------- #
def wordmark_cells() -> list[list[Cell]]:
    """TENDER in the disc's blue, as half-blocks.

    Built and shipped so a banner can use it; nothing reads it today, which is
    stated where it is installed rather than inferred from its not being
    imported.
    """
    import json  # noqa: PLC0415 — read once, at build time

    metrics = json.loads((HERE / "wordmark.json").read_text(encoding="utf-8"))
    path = (HERE / "wordmark.path").read_text(encoding="utf-8").strip()
    width, height = metrics["width"], metrics["height"]
    pixel_height = 256
    pixel_width = round(pixel_height * width / height)
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{pixel_width}" height="{pixel_height}" '
        f'viewBox="0 0 {width} {height}"><path d="{path}" fill="{disc_tone()}"/></svg>'
    )
    rendered = subprocess.run(
        ["rsvg-convert", "-f", "png", "-w", str(pixel_width), "-h", str(pixel_height)],
        input=svg.encode("utf-8"),
        capture_output=True,
        check=True,
    ).stdout
    image = decode_png(rendered)
    box = (0.0, 0.0, float(image.width), float(image.height))
    return half_block_cells(composite(box_sample(image, box, WORDMARK_COLUMNS, WORDMARK_ROWS * 2)))


# --------------------------------------------------------------------------- #
# Escapes                                                                     #
# --------------------------------------------------------------------------- #
_CUBE = (0, 95, 135, 175, 215, 255)


@functools.lru_cache(maxsize=None)
def nearest_256(colour: tuple[int, int, int]) -> int:
    """The 256-colour index closest to *colour*, cube and greys both considered."""
    red, green, blue = colour
    best, best_distance = 16, None
    for i, cube_r in enumerate(_CUBE):
        for j, cube_g in enumerate(_CUBE):
            for k, cube_b in enumerate(_CUBE):
                distance = (cube_r - red) ** 2 + (cube_g - green) ** 2 + (cube_b - blue) ** 2
                if best_distance is None or distance < best_distance:
                    best, best_distance = 16 + 36 * i + 6 * j + k, distance
    for step in range(24):
        level = 8 + 10 * step
        distance = (level - red) ** 2 + (level - green) ** 2 + (level - blue) ** 2
        if best_distance is None or distance < best_distance:
            best, best_distance = 232 + step, distance
    return best


def _sgr(foreground: Pixel, background: Pixel, depth: str) -> str:
    parts = []
    if foreground is None:
        parts.append("39")
    elif depth == "256":
        parts.append(f"38;5;{nearest_256(foreground)}")
    else:
        parts.append("38;2;{};{};{}".format(*foreground))
    if background is None:
        parts.append("49")
    elif depth == "256":
        parts.append(f"48;5;{nearest_256(background)}")
    else:
        parts.append("48;2;{};{};{}".format(*background))
    return "\\033[" + ";".join(parts) + "m"


def block_row(cells: list[Cell], depth: str, width: int) -> str:
    """One row of half-blocks as an escape string, padded to *width* columns.

    Padded rather than trimmed, because the greeter puts a text block beside the
    icon: a row whose width is known without counting is a row a caller can
    align against without measuring a string that has escapes in it. Only the
    colour CHANGES are written, so the row costs one escape per change rather
    than one per cell.

    **The padding goes after the reset.** A row that came up short would
    otherwise have its spaces painted in the last cell's background colour,
    which on a terminal is a bar of that colour running off the end of the mark.
    """
    out = ""
    current: tuple[Pixel, Pixel] | None = None
    for character, foreground, background in cells:
        wanted = (None, background) if character == " " else (foreground, background)
        if wanted != current:
            out += _sgr(*wanted, depth)
            current = wanted
        out += character
    return out + "\\033[0m" + " " * max(0, width - len(cells))


def runs(cells: list[tuple[str, str]], width: int) -> str:
    """One ASCII row as ``class:text`` runs, so the installer splits rather than parses."""
    padded = [*cells, *[(" ", RING)] * max(0, width - len(cells))]
    out: list[list[str]] = []
    for character, colour in padded:
        if out and out[-1][0] == colour:
            out[-1][1] += character
        else:
            out.append([colour, character])
    for _colour, text in out:
        if RUN_SEPARATOR in text:
            raise ValueError(f"a run contains the separator {RUN_SEPARATOR!r}: {text!r}")
    return RUN_SEPARATOR.join(f"{colour}:{text}" for colour, text in out)


RUN_SEPARATOR = "|"


# --------------------------------------------------------------------------- #
# What install.sh embeds                                                      #
# --------------------------------------------------------------------------- #
def _rgb(hex_colour: str) -> str:
    return ";".join(str(int(hex_colour[i : i + 2], 16)) for i in (1, 3, 5))


def tones() -> tuple[str, str]:
    """The two colours the ASCII drawing is written in, as ``#rrggbb``.

    **Both are read from the palette `build.py` ships**, so the drawing cannot
    end up in a colour the mark is not in — which is what a tone written down
    here would eventually be, since the palette the build chooses can change and
    a literal cannot follow it.

    The ring takes the DISC's tone rather than the mark's own navy ink: the
    ASCII drawing has no disc behind it, and navy on a dark terminal is not
    there at all. It is therefore the same blue as the success line, which is
    the point — one run, one blue.
    """
    import gen  # noqa: PLC0415 — a sibling module, resolved through the path build.py sets

    return disc_tone(), gen.BY_NAME[gen.CHOSEN].dot_peach


def disc_tone() -> str:
    """The disc's upper facet tone, as ``#rrggbb`` — what the installer's success line is set in.

    Read from the palette `build.py` ships, so the one coloured sentence of a
    run is the same blue as the disc drawn above it.
    """
    import gen  # noqa: PLC0415 — a sibling module, resolved through the path build.py sets

    return gen.BY_NAME[gen.CHOSEN].disc[0]


def _cube_index(hex_colour: str) -> int:
    return nearest_256(tuple(int(hex_colour[i : i + 2], 16) for i in (1, 3, 5)))


def bash_block() -> str:
    """The generated block `install.sh` carries, markers included."""
    icon = icon_cells()
    drawing = ascii_cells()
    ring, button = tones()
    disc = disc_tone()
    lines = [
        _MARKERS[0],
        f"LOGO_RUN_SEPARATOR={_quote(RUN_SEPARATOR)}",
        f"LOGO_ICON_WIDTH={ICON_COLUMNS}",
        f"LOGO_ASCII_WIDTH={ASCII_COLUMNS}",
        f"LOGO_RING_RGB={_quote(_rgb(ring))}",
        f"LOGO_BUTTON_RGB={_quote(_rgb(button))}",
        f"LOGO_DISC_RGB={_quote(_rgb(disc))}",
        f"LOGO_RING_256={_cube_index(ring)}",
        f"LOGO_BUTTON_256={_cube_index(button)}",
        f"LOGO_DISC_256={_cube_index(disc)}",
        "LOGO_ICON_TRUECOLOR=(",
        *[f"    {_ansi_quote(block_row(row, 'truecolor', ICON_COLUMNS))}" for row in icon],
        ")",
        "LOGO_ICON_256=(",
        *[f"    {_ansi_quote(block_row(row, '256', ICON_COLUMNS))}" for row in icon],
        ")",
        "LOGO_ASCII=(",
        *[f"    {_quote(runs(row, ASCII_COLUMNS))}" for row in drawing],
        ")",
        _MARKERS[1],
    ]
    return "\n".join(lines) + "\n"


def _quote(text: str) -> str:
    """A single-quoted bash word. The art holds no quote, and says so if it ever does."""
    if "'" in text:
        raise ValueError(f"the art contains a single quote, which this quoting cannot carry: {text!r}")
    return f"'{text}'"


def _ansi_quote(text: str) -> str:
    """A `$'…'` bash word, which is what turns the `\\033` below into an escape.

    Written as `\\033` rather than as the byte it stands for: a script carrying
    raw escape bytes is one an editor, a diff or a terminal can mangle without
    anyone seeing it happen.
    """
    if "'" in text:
        raise ValueError(f"the art contains a single quote, which this quoting cannot carry: {text!r}")
    return f"$'{text}'"


# Where the wordmark's two shipped copies live. Two because they answer two
# questions: the `.ans` is what a banner would print, and the `.txt` is what a
# diff can read when the `.ans` changes.
WORDMARK_FILES = (
    (REPO / "assets" / "wordmark-terminal.ans", lambda: wordmark_ansi()),
    (REPO / "assets" / "wordmark-terminal.txt", lambda: wordmark_plain()),
)


class MarkersMissing(Exception):
    """The script being written has no block for the generated art to go in.

    Its own class rather than the `ValueError` a string search raises, because
    the caller can say something useful about it — a traceback out of `str.index`
    names neither the file nor the marker it went looking for.
    """


def replace_in(script: str) -> str:
    """*script* with its generated block swapped for today's."""
    try:
        start = script.index(_MARKERS[0])
        end = script.index(_MARKERS[1]) + len(_MARKERS[1]) + 1
    except ValueError as missing:
        raise MarkersMissing(_MARKERS[0]) from missing
    return script[:start] + bash_block() + script[end:]


# --------------------------------------------------------------------------- #
# The wordmark's two shipped files                                            #
# --------------------------------------------------------------------------- #
def wordmark_ansi() -> str:
    """The wordmark as escapes, ready to `cat`."""
    rows = wordmark_cells()
    return "\n".join(block_row(row, "truecolor", WORDMARK_COLUMNS).replace("\\033", "\033") for row in rows) + "\n"


def wordmark_plain() -> str:
    """The wordmark's glyphs with the colour taken out, for a diff to read."""
    return plain(wordmark_cells())


def plain(rows: list[list[Cell]]) -> str:
    """The characters of a half-block drawing, colour dropped."""
    return "\n".join("".join(character for character, _fg, _bg in row).rstrip() for row in rows) + "\n"


if __name__ == "__main__":
    if "--wordmark" in sys.argv:
        sys.stdout.write(wordmark_ansi())
    elif "--preview" in sys.argv:
        sys.stdout.write("\n".join(block_row(row, "truecolor", ICON_COLUMNS).replace("\\033", "\033") for row in icon_cells()))
        sys.stdout.write("\n\n")
        for row in ascii_cells():
            print("".join(character for character, _colour in row).rstrip())
    elif "--plain" in sys.argv:
        sys.stdout.write(plain(icon_cells()))
    else:
        print(bash_block(), end="")
