#!/usr/bin/env python3
"""The mark as terminal text, in Braille cells and in ASCII.

`install.sh` is the first thing a user of this program sees, and it draws the
mark before it does anything. It cannot render an image and it must not grow a
dependency to do it, so the art is TEXT embedded in the script — and text
embedded in a script is the kind of thing that gets hand-tidied until it no
longer resembles what it is a picture of. It is checked against this module by
`scripts/check_generated_installer_logo.py`.

**The terminal mark shares the tab icon's pose, and is rendered rather than
read.** The shipped mark turns its sync ring by `arc_rot` so the ring follows
the disc's facet; at this size that lands the ring's two gaps off the
horizontal, where a gap half a cell high reads as a lopsided ring rather than as
a turn. `tabicon.STRIP_GEOMETRY` zeroes the same field for the same reason. So
the source here is not `assets/logo.png` — it is `gen.standalone` drawn with
that pose and rasterised by `rsvg-convert`, which is the only way to change the
pose without turning a raster: rotating the shipped PNG would smear the four
dots into ellipses and soften every edge the classifier reads.

Two renderings, because one of them cannot always be shown:

* **Braille**, 24 columns by 10 rows. Each cell carries 2x4 dots, so the picture
  is 48 by 40 dots in the space of 24 characters — far more resolution than any
  glyph set. It needs a UTF-8 locale.
* **ASCII**, 26 columns by 13 rows, drawn in the weight of the ink rather than
  in dots, for a terminal that has no UTF-8.

**Every pixel is classified before anything is scaled**, and cells are built by
counting classes over the pixels they cover. Scaling first and classifying the
result would invent colours on every edge — a blend of navy ink and light disc
is neither, and the hue test would then answer for a pixel that is not in the
image.

**The four buttons are the exception: they are DRAWN, not sampled.** Counting
over a circle's rim frays it, and the four dots came out four different shapes;
see :class:`Buttons`.

The PNG is decoded here rather than with an imaging library: this module and its
check have to run wherever the repository's lint runs, which is a Python and
nothing else.
"""

from __future__ import annotations

import colorsys
import dataclasses
import functools
import math
import pathlib
import struct
import subprocess
import zlib

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent

# What the mark is rasterised at before it is sampled. The drawing is a
# 200-unit square, so this is about ten source pixels per Braille dot — enough
# that a dot's coverage is a count rather than a coin toss, and small enough
# that classifying every pixel stays a second's work.
RENDER_SIZE = 1024

BRAILLE_COLUMNS = 24
BRAILLE_ROWS = 10
ASCII_COLUMNS = 26
ASCII_ROWS = 13

# The two tones the installer draws the mark in. `b` is the button's warm
# accent, `r` everything else that carries ink, `_` a cell with nothing in it.
# Not the mark's own colours: the ink is NAVY, and on a dark terminal navy dots
# on a black ground are not there at all — so the cells that are ink take the
# DISC's light blue instead, which is the tone that reads on both grounds.
BUTTON = "b"
RING = "r"
EMPTY = "_"

# A cell is the button's when this much of it is. Below it the button's edge is
# a rim on a cell that is mostly something else, and colouring the whole cell
# for it spreads the accent over the arrow beside it.
BUTTON_SHARE = 0.34

_MARKERS = (
    "# >>> generated by scripts/logo/terminal.py — do not edit",
    "# <<< generated",
)


# --------------------------------------------------------------------------- #
# Reading the image                                                           #
# --------------------------------------------------------------------------- #
class Image:
    """An 8-bit RGBA raster, addressed by pixel."""

    def __init__(self, width: int, height: int, pixels: bytes) -> None:
        self.width = width
        self.height = height
        self.pixels = pixels

    def at(self, x: int, y: int) -> tuple[int, int, int, int]:
        start = (y * self.width + x) * 4
        r, g, b, a = self.pixels[start : start + 4]
        return r, g, b, a


def render_source(size: int = RENDER_SIZE) -> Image:
    """Draw the mark in the terminal's pose and rasterise it.

    The pose is the tab icon's: the sync ring unrotated, so its two gaps sit on
    one horizontal line. The disc's facet goes with it — the seam is a tone
    difference this classifier does not see, and one less thing in the raster is
    one less thing to explain.

    Needs `rsvg-convert`, which every other rasterising step of
    `scripts/logo/build.py` needs too.
    """
    import gen  # noqa: PLC0415 — a sibling module, resolved through the path build.py sets

    palette = gen.BY_NAME[gen.CHOSEN]
    flat = dataclasses.replace(palette, disc=(palette.disc[0], palette.disc[0]))
    pose = dataclasses.replace(gen.DEFAULT_GEOMETRY, arc_rot=0.0)
    svg = gen.standalone(flat, pose, size=size)
    rendered = subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size)],
        input=svg.encode("utf-8"),
        capture_output=True,
        check=True,
    ).stdout
    return decode_png(rendered)


def decode_png(data: bytes) -> Image:
    """Decode a non-interlaced 8-bit RGBA PNG.

    Refuses anything else rather than guessing: what this reads is what
    `rsvg-convert` emits, so a different shape means that changed and the reader
    has to be looked at rather than coaxed.
    """
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    width = height = 0
    body = bytearray()
    position = 8
    while position < len(data):
        (length,) = struct.unpack(">I", data[position : position + 4])
        kind = data[position + 4 : position + 8]
        chunk = data[position + 8 : position + 8 + length]
        if kind == b"IHDR":
            width, height, depth, colour, compression, filtering, interlace = struct.unpack(">IIBBBBB", chunk)
            if (depth, colour, compression, filtering, interlace) != (8, 6, 0, 0, 0):
                raise ValueError(f"expected 8-bit RGBA, non-interlaced, got {chunk[8:]!r}")
        elif kind == b"IDAT":
            body += chunk
        elif kind == b"IEND":
            break
        position += 12 + length
    return Image(width, height, _unfilter(zlib.decompress(bytes(body)), width, height))


def _unfilter(raw: bytes, width: int, height: int) -> bytes:
    """Undo PNG's per-scanline filters, answering the pixel bytes.

    Each scanline is preceded by one byte naming its filter, and every filter
    but the first predicts a byte from its neighbours — so this cannot be done
    out of order or in parallel: row N is decoded against the already-decoded
    row N-1.
    """
    stride = width * 4
    out = bytearray(stride * height)
    position = 0
    for y in range(height):
        filter_kind = raw[position]
        position += 1
        line = bytearray(raw[position : position + stride])
        position += stride
        above = out[(y - 1) * stride : y * stride] if y else bytes(stride)
        for x in range(stride):
            left = line[x - 4] if x >= 4 else 0
            up = above[x]
            upper_left = above[x - 4] if x >= 4 else 0
            if filter_kind == 1:
                line[x] = (line[x] + left) & 0xFF
            elif filter_kind == 2:
                line[x] = (line[x] + up) & 0xFF
            elif filter_kind == 3:
                line[x] = (line[x] + (left + up) // 2) & 0xFF
            elif filter_kind == 4:
                line[x] = (line[x] + _paeth(left, up, upper_left)) & 0xFF
            elif filter_kind != 0:
                raise ValueError(f"unknown PNG filter {filter_kind} on row {y}")
        out[y * stride : (y + 1) * stride] = line
    return bytes(out)


def _paeth(left: int, up: int, upper_left: int) -> int:
    estimate = left + up - upper_left
    da, db, dc = abs(estimate - left), abs(estimate - up), abs(estimate - upper_left)
    if da <= db and da <= dc:
        return left
    return up if db <= dc else upper_left


# --------------------------------------------------------------------------- #
# What each pixel is                                                          #
# --------------------------------------------------------------------------- #
BG, DISC, ARROW, BUTTON_PIXEL = "bg", "disc", "arrow", "button"

# What each rendering draws, and so what each one crops to.
INK_ONLY = frozenset({ARROW, BUTTON_PIXEL})
EVERYTHING_DRAWN = frozenset({DISC, ARROW, BUTTON_PIXEL})


# The raster is flat fills and the edges between them, so a million pixels carry
# a few thousand distinct colours. Cached, the hue arithmetic runs once per
# colour instead of once per pixel.
@functools.lru_cache(maxsize=None)
def classify(r: int, g: int, b: int, a: int) -> str:
    """Which part of the mark a pixel belongs to.

    By hue and lightness rather than by exact colour, because the mark is drawn
    with two-tone facets and antialiased edges: an equality test against the
    palette would answer for the flat middle of each shape and for nothing else.
    The warm accents — the button and the dots — are the only saturated warm
    thing in the mark, and the ink is the only dark thing.
    """
    if a < 40:
        return BG
    hue, lightness, saturation = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    if saturation > 0.25 and hue < 0.13:
        return BUTTON_PIXEL
    if lightness < 0.30:
        return ARROW
    return DISC


class Classified:
    """The mark's pixels as classes, cropped to the classes *drawn* names.

    **Each rendering crops to what IT draws**, which is why this takes the set
    rather than assuming it. The Braille cells carry only ink, and the disc's
    bottom rim is not ink — cropping those to the whole mark spends the last row
    of ten on the blank below the lower arrow. The ASCII rendering does draw the
    rim, so it crops to the whole mark and comes out round.
    """

    def __init__(self, image: Image, drawn_classes: frozenset[str]) -> None:
        classes = [[classify(*image.at(x, y)) for x in range(image.width)] for y in range(image.height)]
        drawn = [(x, y) for y in range(image.height) for x in range(image.width) if classes[y][x] in drawn_classes]
        left = min(x for x, _y in drawn)
        right = max(x for x, _y in drawn)
        top = min(y for _x, y in drawn)
        bottom = max(y for _x, y in drawn)
        self.width = right - left + 1
        self.height = bottom - top + 1
        self.rows = [row[left : right + 1] for row in classes[top : bottom + 1]]

    def share(self, x0: float, y0: float, x1: float, y1: float) -> dict[str, float]:
        """What fraction of the box is each class, sampled over its pixels."""
        counts = dict.fromkeys((BG, DISC, ARROW, BUTTON_PIXEL), 0)
        total = 0
        for y in range(max(0, int(y0)), min(self.height, max(int(y0) + 1, int(y1)))):
            for x in range(max(0, int(x0)), min(self.width, max(int(x0) + 1, int(x1)))):
                counts[self.rows[y][x]] += 1
                total += 1
        if not total:
            return dict.fromkeys(counts, 0.0)
        return {name: count / total for name, count in counts.items()}


# --------------------------------------------------------------------------- #
# The buttons, which are drawn rather than sampled                            #
# --------------------------------------------------------------------------- #
# How far past its own colour a button reaches, as a FRACTION of its radius.
# The four dots sit ON the dark bars, so each one is ringed by a thin band of
# bar that classifies as ink — and ink is drawn in the ring's blue, which put a
# blue outline around every button. Growing the button by this much takes that
# band with it.
#
# A fraction rather than a count of pixels: the band is part of the drawing and
# scales with it, so a count would mean something different at every
# :data:`RENDER_SIZE`.
BUTTON_OUTLINE = 0.09


class Buttons:
    """The mark's four round buttons: where their centres are, and how big.

    **They are stamped, not sampled.** A cell that takes its value from a
    majority of the pixels under it frays a circle's edge — the cells on the rim
    flip one way or the other on a fraction of a pixel, and the four buttons end
    up four different shapes. A disc drawn from a centre and a radius is
    symmetric because the test is, and all four come out identical because the
    radius is shared and the centre is snapped to a whole sub-cell.

    The radius is the one the AREA implies rather than the widest span, so a
    button whose rim the classifier read a pixel too far does not grow.
    """

    def __init__(self, source: Classified) -> None:
        found = [_component_shape(cells) for cells in _components(source, BUTTON_PIXEL)]
        if len(found) != 4:
            raise ValueError(f"expected four buttons in the mark, found {len(found)}")
        self.centres = [(x, y) for x, y, _radius in found]
        self.radius = sum(radius for _x, _y, radius in found) / len(found) * (1 + BUTTON_OUTLINE)

    def covers(self, x: float, y: float) -> bool:
        """Whether a source pixel belongs to a button, rim included."""
        return any((x - cx) ** 2 + (y - cy) ** 2 <= self.radius**2 for cx, cy in self.centres)


# Below this a run of button-coloured pixels is an artefact of the edge between
# two other colours rather than a button.
_SPECK = 50


def _components(source: Classified, wanted: str) -> list[list[tuple[int, int]]]:
    """Every connected run of *wanted* pixels, largest first, specks dropped.

    Four-connected, and iterative rather than recursive: a component here is
    several thousand pixels, which is deeper than Python will recurse.
    """
    seen = [[False] * source.width for _ in range(source.height)]
    found = []
    for top in range(source.height):
        for left in range(source.width):
            if seen[top][left] or source.rows[top][left] != wanted:
                continue
            stack, cells = [(left, top)], []
            seen[top][left] = True
            while stack:
                x, y = stack.pop()
                cells.append((x, y))
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < source.width and 0 <= ny < source.height and not seen[ny][nx]:
                        if source.rows[ny][nx] == wanted:
                            seen[ny][nx] = True
                            stack.append((nx, ny))
            if len(cells) > _SPECK:
                found.append(cells)
    return sorted(found, key=len, reverse=True)


def _component_shape(cells: list[tuple[int, int]]) -> tuple[float, float, float]:
    """A component's centre and the radius its area implies."""
    return (
        sum(x for x, _y in cells) / len(cells),
        sum(y for _x, y in cells) / len(cells),
        math.sqrt(len(cells) / math.pi),
    )


# --------------------------------------------------------------------------- #
# The two renderings                                                          #
# --------------------------------------------------------------------------- #
# Which bit each dot of a Braille cell carries. The first six are the historic
# 6-dot cell, read down the left column and then down the right; the two at the
# bottom were added for 8-dot Braille and sit above the high bits.
_DOT_BITS = ((0, 0, 0x01), (0, 1, 0x02), (0, 2, 0x04), (1, 0, 0x08), (1, 1, 0x10), (1, 2, 0x20), (0, 3, 0x40), (1, 3, 0x80))


def _stamped(source: Classified, buttons: Buttons, across: int, down: int, squash: float) -> list[list[bool]]:
    """A sub-cell grid with a button's disc drawn into it, ``[row][column]``.

    *squash* is what a step sideways is worth against a step down. A Braille dot
    is square, so it is 1; an ASCII character is about twice as tall as it is
    wide, so it is 0.5 and the disc comes out twice as wide as it is tall — which
    is round on screen.

    The centre is snapped to a whole sub-cell so that all four stamps are the
    same set of offsets. Without that, four centres at four sub-cell fractions
    round four different ways and the buttons stop matching each other.

    The radius is NOT rounded to a half sub-cell. It is the radius the removal
    used, so the disc covers exactly what was taken out; rounding it up leaves
    single sub-cells standing off the disc's four compass points, and rounding it
    down leaves a rim of the ink it replaced.
    """
    radius = buttons.radius * (across / source.width + down / source.height) / 2
    grid = [[False] * across for _ in range(down)]
    for centre_x, centre_y in buttons.centres:
        snapped_x = math.floor(centre_x / source.width * across) + 0.5
        snapped_y = math.floor(centre_y / source.height * down) + 0.5
        for row in range(down):
            for column in range(across):
                dx = (column + 0.5 - snapped_x) * squash
                dy = row + 0.5 - snapped_y
                if dx * dx + dy * dy <= radius * radius:
                    grid[row][column] = True
    return grid


def braille_cells(source: Classified, buttons: Buttons) -> list[list[tuple[str, str]]]:
    """The Braille rendering as rows of ``(character, colour class)``."""
    dots_across, dots_down = BRAILLE_COLUMNS * 2, BRAILLE_ROWS * 4
    dot_w, dot_h = source.width / dots_across, source.height / dots_down
    stamp = _stamped(source, buttons, dots_across, dots_down, 1.0)
    rows = []
    for row in range(BRAILLE_ROWS):
        cells = []
        for column in range(BRAILLE_COLUMNS):
            bits = 0
            stamped = False
            for dx, dy, bit in _DOT_BITS:
                across, down = column * 2 + dx, row * 4 + dy
                if stamp[down][across]:
                    bits |= bit
                    stamped = True
                    continue
                x, y = across * dot_w, down * dot_h
                if _ink_share(source, buttons, x, y, x + dot_w, y + dot_h) >= 0.5:
                    bits |= bit
            colour = EMPTY if not bits else (BUTTON if stamped else RING)
            cells.append((chr(0x2800 + bits) if bits else " ", colour))
        rows.append(cells)
    return rows


def _ink_share(source: Classified, buttons: Buttons, x0: float, y0: float, x1: float, y1: float) -> float:
    """How much of a box is ink that no button has claimed."""
    total = ink = 0
    for y in range(max(0, int(y0)), min(source.height, max(int(y0) + 1, int(y1)))):
        for x in range(max(0, int(x0)), min(source.width, max(int(x0) + 1, int(x1)))):
            total += 1
            if source.rows[y][x] in (ARROW, BUTTON_PIXEL) and not buttons.covers(x, y):
                ink += 1
    return ink / total if total else 0.0


def ascii_cells(source: Classified, buttons: Buttons) -> list[list[tuple[str, str]]]:
    """The ASCII rendering as rows of ``(character, colour class)``.

    Drawn in weights rather than dots: three for the arrows by how much of the
    cell they cover, two for the buttons — the solid middle and the rim of the
    stamped disc — and a single ``.`` for the disc's rim, which is the only thing
    that gives the mark its outline when there are no dots to draw it with.
    """
    cell_w, cell_h = source.width / ASCII_COLUMNS, source.height / ASCII_ROWS
    stamp = _stamped(source, buttons, ASCII_COLUMNS, ASCII_ROWS, 0.5)
    rows = []
    for row in range(ASCII_ROWS):
        cells = []
        for column in range(ASCII_COLUMNS):
            if stamp[row][column]:
                cells.append(("@" if _all_neighbours_stamped(stamp, row, column) else "O", BUTTON))
                continue
            share = source.share(column * cell_w, row * cell_h, (column + 1) * cell_w, (row + 1) * cell_h)
            arrow = _ink_share(source, buttons, column * cell_w, row * cell_h, (column + 1) * cell_w, (row + 1) * cell_h)
            if arrow >= 0.5:
                cells.append(("#", RING))
            elif arrow >= 0.25:
                cells.append(("+", RING))
            elif arrow >= 0.1:
                cells.append(("-", RING))
            elif share[DISC] > 0 and share[BG] > 0.15:
                cells.append((".", RING))
            else:
                cells.append((" ", EMPTY))
        rows.append(cells)
    return rows


def _all_neighbours_stamped(stamp: list[list[bool]], row: int, column: int) -> bool:
    """Whether a stamped cell is in the disc's middle rather than on its edge."""
    for dy in (-1, 0, 1):
        for dx in (-1, 0, 1):
            y, x = row + dy, column + dx
            if not (0 <= y < len(stamp) and 0 <= x < len(stamp[0])) or not stamp[y][x]:
                return False
    return True


# --------------------------------------------------------------------------- #
# What install.sh embeds                                                      #
# --------------------------------------------------------------------------- #
RUN_SEPARATOR = "|"


def runs(cells: list[tuple[str, str]]) -> str:
    """One row as ``class:text`` runs, so the installer splits rather than parses.

    Neighbouring cells of one colour become one run, which is what keeps the
    number of escape sequences down to the number of colour changes. Every row
    is emitted at its full width, trailing spaces and all: a row whose width is
    known without counting is a row the caller can put a text block beside
    without measuring anything that has escapes in it.
    """
    out = []
    for character, colour in cells:
        if out and out[-1][0] == colour:
            out[-1][1] += character
        else:
            out.append([colour, character])
    for _colour, text in out:
        if RUN_SEPARATOR in text:
            raise ValueError(f"a run contains the separator {RUN_SEPARATOR!r}: {text!r}")
    return RUN_SEPARATOR.join(f"{colour}:{text}" for colour, text in out)


# The xterm-256 cube's six levels per channel, and the greys above it. Both are
# fixed by the terminal, not chosen here.
_CUBE_LEVELS = (0, 95, 135, 175, 215, 255)


def nearest_256(hex_colour: str) -> int:
    """The 256-colour index closest to *hex_colour*, cube and greys both considered."""
    want = tuple(int(hex_colour[i : i + 2], 16) for i in (1, 3, 5))

    def distance(candidate: tuple[int, int, int]) -> int:
        return sum((a - b) ** 2 for a, b in zip(want, candidate, strict=True))

    best_index, best_distance = 0, None
    for index in range(16, 232):
        offset = index - 16
        candidate = (
            _CUBE_LEVELS[offset // 36],
            _CUBE_LEVELS[(offset // 6) % 6],
            _CUBE_LEVELS[offset % 6],
        )
        if best_distance is None or distance(candidate) < best_distance:
            best_index, best_distance = index, distance(candidate)
    for index in range(232, 256):
        level = 8 + (index - 232) * 10
        if distance((level, level, level)) < best_distance:
            best_index, best_distance = index, distance((level, level, level))
    return best_index


def _rgb(hex_colour: str) -> str:
    return ";".join(str(int(hex_colour[i : i + 2], 16)) for i in (1, 3, 5))


def tones() -> tuple[str, str]:
    """The two colours the terminal mark is drawn in, as ``#rrggbb``.

    Read from the palette `build.py` ships rather than written down here, so the
    drawing cannot end up in colours the mark is not in. **Not the mark's own
    pairing**: what the Braille cells carry is the INK, and the ink is navy —
    invisible on a dark terminal — so the cells that are ink take the DISC's
    light blue, which is the one tone in the mark that reads on either ground.
    """
    import gen  # noqa: PLC0415 — a sibling module, resolved through the path build.py sets

    palette = gen.BY_NAME[gen.CHOSEN]
    return palette.disc[0], palette.dot_peach


def bash_block() -> str:
    """The generated block `install.sh` carries, markers included."""
    image = render_source()
    ink = Classified(image, INK_ONLY)
    whole = Classified(image, EVERYTHING_DRAWN)
    braille = braille_cells(ink, Buttons(ink))
    ascii_art = ascii_cells(whole, Buttons(whole))
    ring, button = tones()
    lines = [
        _MARKERS[0],
        f"LOGO_RUN_SEPARATOR={_quote(RUN_SEPARATOR)}",
        f"LOGO_RING_RGB={_quote(_rgb(ring))}",
        f"LOGO_BUTTON_RGB={_quote(_rgb(button))}",
        f"LOGO_RING_256={nearest_256(ring)}",
        f"LOGO_BUTTON_256={nearest_256(button)}",
        f"LOGO_BRAILLE_WIDTH={BRAILLE_COLUMNS}",
        f"LOGO_ASCII_WIDTH={ASCII_COLUMNS}",
        "LOGO_BRAILLE=(",
        *[f"    {_quote(runs(row))}" for row in braille],
        ")",
        "LOGO_ASCII=(",
        *[f"    {_quote(runs(row))}" for row in ascii_art],
        ")",
        _MARKERS[1],
    ]
    return "\n".join(lines) + "\n"


def _quote(text: str) -> str:
    """A single-quoted bash word. The art holds no quote, and says so if it ever does."""
    if "'" in text:
        raise ValueError(f"the art contains a single quote, which this quoting cannot carry: {text!r}")
    return f"'{text}'"


def replace_in(script: str) -> str:
    """*script* with its generated block swapped for today's."""
    start = script.index(_MARKERS[0])
    end = script.index(_MARKERS[1]) + len(_MARKERS[1]) + 1
    return script[:start] + bash_block() + script[end:]


if __name__ == "__main__":
    import sys

    if "--preview" in sys.argv:
        loaded = render_source()
        ink = Classified(loaded, INK_ONLY)
        whole = Classified(loaded, EVERYTHING_DRAWN)
        for row in braille_cells(ink, Buttons(ink)):
            print("".join(character for character, _colour in row))
        print()
        for row in ascii_cells(whole, Buttons(whole)):
            print("".join(character for character, _colour in row))
    else:
        print(bash_block(), end="")
