"""A RomM collection's Steam name under the collection naming mode.

The pure kernel behind the ``merge`` / ``by_label`` Steam-collection naming
modes: it maps a collection's ``kind`` (``standard`` / ``smart`` / ``virtual``)
and, for the virtual kind, its ``virtual_type`` (``franchise`` / ``collection``)
onto the label appended to the collection's Steam name, or onto none, and builds
that name. No I/O, no state.

The rule the labels follow, and where else they are spelled (so what a change
here must also change): ``docs/architecture/steam-non-steam-shortcuts.md``
§ Collection naming mode.

Label-format safety: a label is appended inside the single bracket pair of
``RomM: [<name> (<label>)]``, and the frontend reconcile parses that name with
``/^RomM: \\[([^\\]]+)\\]/`` (``frontend/src/index.tsx``). So a label must
contain **no** ``]`` character (parens are safe, brackets would truncate the
parsed name and orphan the collection). Every label below is bracket-free; the
fallback capitalises a controlled kind literal, which is too.
"""

from __future__ import annotations

# Coarse kind → label.
_KIND_LABELS: dict[str, str] = {
    "smart": "Smart",
    "virtual": "Autogenerated",
}

# Virtual sub-type → label.
_VIRTUAL_TYPE_LABELS: dict[str, str] = {
    "franchise": "Franchise",
    "collection": "IGDB Collection",
}


def collection_label(kind: str, virtual_type: str | None) -> str | None:
    """Return the type label for a collection of ``kind`` / ``virtual_type``.

    ``standard`` → ``None``: a standard collection carries no label.
    ``smart`` → ``"Smart"``. A ``virtual`` collection resolves to its
    virtual-type label — ``franchise`` → ``"Franchise"``, ``collection`` →
    ``"IGDB Collection"`` — falling back to ``"Autogenerated"`` when the type is
    missing or unrecognised, which the sync never produces: it fetches only the
    two known virtual types. An unknown ``kind`` degrades to the capitalised
    kind string (never expected for the ``standard`` / ``smart`` / ``virtual``
    set), and an empty kind to ``"Collection"``. Every label is free of ``]``
    so the reconcile name-parse stays intact.
    """
    if kind == "standard":
        return None
    if kind == "virtual":
        if virtual_type is not None and virtual_type in _VIRTUAL_TYPE_LABELS:
            return _VIRTUAL_TYPE_LABELS[virtual_type]
        return _KIND_LABELS["virtual"]
    if kind in _KIND_LABELS:
        return _KIND_LABELS[kind]
    return kind.capitalize() if kind else "Collection"


def steam_collection_key(name: str, kind: str, virtual_type: str | None, naming_mode: str) -> str:
    """Return the Steam-collection name-part for a collection under *naming_mode*.

    ``merge`` (the default, and any unknown mode) → the bare display name.
    ``by_label`` → ``"<name> (<label>)"`` with the label from
    :func:`collection_label`, or the bare name where that gives none (a
    standard collection). The frontend wraps the result as ``RomM: [<key>]``.
    Every reader of a collection's Steam name takes it from here: the
    reporter's union key, and the preview's collection diff, which compares it
    against the keys the last completed run recorded
    (``docs/architecture/steam-non-steam-shortcuts.md`` § Collection naming mode).
    """
    if naming_mode == "by_label":
        label = collection_label(kind, virtual_type)
        if label is not None:
            return f"{name} ({label})"
    return name
