"""Type label for a RomM collection's Steam name, keyed by kind + virtual type.

The pure kernel behind the ``by_label`` Steam-collection naming mode: it maps a
collection's ``kind`` (``standard`` / ``smart`` / ``virtual``) and, for the
virtual kind, its ``virtual_type`` (``franchise`` / ``collection``) onto the
label the reporter appends to the collection's Steam name, or onto none. No
I/O, no state.

The rule the labels follow, and where else they are spelled (so what a change
here must also change): ``docs/architecture/steam-non-steam-shortcuts.md``
§ Collection naming mode.

Label-format safety: a label is appended inside the single bracket pair of
``RomM: [<name> (<label>)]``, and the frontend reconcile parses that name with
``/^RomM: \\[([^\\]]+)\\]/`` (``frontend/src/index.tsx``). So a label must
contain **no** ``]`` character (parens are safe, brackets would truncate the
parsed name and orphan the collection). Every label below is bracket-free; the
fallback capitalises a controlled kind literal, which is too.
"""

from __future__ import annotations

# Coarse kind → label.
_KIND_LABELS: dict[str, str] = {
    "smart": "Smart",
    "virtual": "Autogenerated",
}

# Virtual sub-type → label.
_VIRTUAL_TYPE_LABELS: dict[str, str] = {
    "franchise": "Franchise",
    "collection": "IGDB Collection",
}


def collection_label(kind: str, virtual_type: str | None) -> str | None:
    """Return the type label for a collection of ``kind`` / ``virtual_type``.

    ``standard`` → ``None``: a standard collection carries no label.
    ``smart`` → ``"Smart"``. A ``virtual`` collection resolves to its
    virtual-type label — ``franchise`` → ``"Franchise"``, ``collection`` →
    ``"IGDB Collection"`` — falling back to ``"Autogenerated"`` when the type is
    missing or unrecognised, which the sync never produces: it fetches only the
    two known virtual types. An unknown ``kind`` degrades to the capitalised
    kind string (never expected for the ``standard`` / ``smart`` / ``virtual``
    set), and an empty kind to ``"Collection"``. Every label is free of ``]``
    so the reconcile name-parse stays intact.
    """
    if kind == "standard":
        return None
    if kind == "virtual":
        if virtual_type is not None and virtual_type in _VIRTUAL_TYPE_LABELS:
            return _VIRTUAL_TYPE_LABELS[virtual_type]
        return _KIND_LABELS["virtual"]
    if kind in _KIND_LABELS:
        return _KIND_LABELS[kind]
    return kind.capitalize() if kind else "Collection"
