"""Tests for ``scripts/check_generated_installer_logo.py`` and the art it guards.

The check is the only thing standing between the installer's greeter and a
hand-tidied copy of a drawing, so what is asserted here is that it notices — one
cell is enough — rather than that it passes today, which a check that always
passed would also manage.

Both modules load via ``importlib`` because ``scripts/`` is not on ``sys.path``.
"""

from __future__ import annotations

import functools
import importlib.util
import re
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from types import ModuleType

_REPO_ROOT = Path(__file__).resolve().parents[2]

# What one half-block cell is: its character, and the colour of each half — None
# where that half is left to the terminal's own background.
_Colour = tuple[int, int, int] | None
_Cell = tuple[str, _Colour, _Colour]
_CHECK_PATH = _REPO_ROOT / "scripts" / "check_generated_installer_logo.py"
_INSTALL = _REPO_ROOT / "install.sh"


def _load(path: Path, name: str) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def generator() -> ModuleType:
    sys.path.insert(0, str(_REPO_ROOT / "scripts" / "logo"))
    return _load(_REPO_ROOT / "scripts" / "logo" / "terminal.py", "terminal")


@functools.lru_cache(maxsize=1)
def _icon(module: ModuleType) -> tuple[tuple[_Cell, ...], ...]:
    """The icon's cells, drawn once for the whole file.

    Cached because every case below wants the same drawing and making it is an
    rsvg-convert run plus a megapixel of box filtering.
    """
    return tuple(tuple(row) for row in module.icon_cells())


@functools.lru_cache(maxsize=1)
def _drawing(module: ModuleType) -> tuple[tuple[tuple[str, str], ...], ...]:
    """The ASCII drawing's cells, drawn once for the whole file."""
    return tuple(tuple(row) for row in module.ascii_cells())


@pytest.fixture
def tree(tmp_path, monkeypatch, generator):
    """A copy of what the check reads, with the check pointed at the copy.

    **No case here writes a tracked file.** The failures this gate exists for
    are all "someone edited the art", so exercising them means editing it — and
    a run killed between the edit and its restore would leave a corrupted
    installer in the working tree for whoever looked next.
    """
    check = _load(_CHECK_PATH, "check_generated_installer_logo")
    installer = tmp_path / "install.sh"
    installer.write_bytes(_INSTALL.read_bytes())
    wordmarks = []
    for destination, render in generator.WORDMARK_FILES:
        copy = tmp_path / destination.name
        copy.write_bytes(destination.read_bytes())
        wordmarks.append((copy, render))
    monkeypatch.setattr(check, "REPO", tmp_path)
    monkeypatch.setattr(check, "GENERATED", installer)
    monkeypatch.setattr(generator, "WORDMARK_FILES", tuple(wordmarks))
    return SimpleNamespace(check=check, installer=installer, wordmark=wordmarks[1][0])


class TestTheCheck:
    def test_the_committed_block_is_what_the_generator_emits(self, tree, capsys):
        assert tree.check.main() == 0
        assert "OK:" in capsys.readouterr().out

    def test_one_edited_cell_is_reported(self, tree, capsys):
        """The failure this exists for: a drawing tidied by hand, one cell at a time."""
        text = tree.installer.read_text(encoding="utf-8")
        edited = text.replace("LOGO_ASCII=(\n    '", "LOGO_ASCII=(\n    'r:", 1)
        assert edited != text
        tree.installer.write_text(edited, encoding="utf-8")

        assert tree.check.main() == 1
        printed = capsys.readouterr().out
        assert "install.sh" in printed
        assert "--terminal" in printed

    def test_an_edited_wordmark_is_reported(self, tree, capsys):
        """It ships two files nothing reads yet, and the check still holds them."""
        tree.wordmark.write_bytes(tree.wordmark.read_bytes() + b"tidied by hand\n")

        assert tree.check.main() == 1
        assert tree.wordmark.name in capsys.readouterr().out

    def test_a_script_with_no_markers_is_told_what_is_missing(self, tree, capsys):
        """A `str.index` traceback names neither the file nor what it went looking for."""
        text = tree.installer.read_text(encoding="utf-8")
        tree.installer.write_text(text.replace("# >>> generated by", "# once generated by", 1), encoding="utf-8")

        assert tree.check.main() == 1
        printed = capsys.readouterr().out
        assert "carries no block for the mark to go in" in printed
        assert "Traceback" not in printed

    def test_without_rsvg_convert_it_says_it_compared_nothing(self, tree, tmp_path, monkeypatch, capsys):
        """It draws the mark to compare it, so it cannot answer without a renderer.

        Answering "not checked" rather than "wrong" is the same shape the tab
        glyph's check takes without prettier, and for the same reason: a
        contributor who has not got the tool is not who this is aimed at.
        """
        empty = tmp_path / "no-tools"
        empty.mkdir()
        monkeypatch.setenv("PATH", str(empty))

        assert tree.check.main() == 0
        assert "NOT CHECKED" in capsys.readouterr().out


class TestTheIcon:
    """Half-blocks, where the two colours of a cell ARE the picture."""

    def test_it_is_the_size_it_says_it_is(self, generator):
        icon = _icon(generator)

        assert len(icon) == generator.icon_rows()
        assert all(len(row) == generator.ICON_COLUMNS for row in icon)

    def test_every_cell_is_a_half_block_or_a_space(self, generator):
        """Nothing is drawn in glyph shapes, so there are only three characters."""
        drawn = {character for row in _icon(generator) for character, _fg, _bg in row}

        assert drawn <= {generator.UPPER_HALF, generator.LOWER_HALF, " "}

    def test_a_space_is_left_to_the_terminal(self, generator):
        """Painting a box the colour of a GUESS at the background is the one thing
        that looks wrong on the terminal the guess was wrong about."""
        for row in _icon(generator):
            for character, foreground, background in row:
                if character == " ":
                    assert foreground is None
                    assert background is None

    def test_it_carries_the_marks_own_colours(self, generator):
        """The real mark, not a silhouette: the warm buttons and the navy ink are in it."""
        colours = [
            colour
            for row in _icon(generator)
            for _character, upper, lower in row
            for colour in (upper, lower)
            if colour
        ]

        assert any(red > 180 and blue < 170 for red, _green, blue in colours), "no warm button tone"
        assert any(sum(colour) < 210 for colour in colours), "no dark ink tone"
        assert any(blue > 200 and red < 190 for red, _green, blue in colours), "no light disc tone"

    def test_the_rows_it_emits_are_padded_to_one_width(self, generator):
        """A caller puts a text block beside it, and cannot measure a string with escapes in it."""
        for row in _icon(generator):
            printable = generator.block_row(row, "truecolor", generator.ICON_COLUMNS)
            stripped = re.sub(r"\\033\[[0-9;]*m", "", printable)

            assert len(stripped) == generator.ICON_COLUMNS

    def test_the_256_colour_form_writes_no_24_bit_escape(self, generator):
        """A terminal that did not say it takes 24-bit colour is not given any."""
        for row in _icon(generator):
            assert "38;2;" not in generator.block_row(row, "256", generator.ICON_COLUMNS)


class TestTheAsciiDrawing:
    """The other technique, for the terminal that cannot show the first one."""

    def test_it_is_the_size_it_says_it_is(self, generator):
        drawing = _drawing(generator)

        assert len(drawing) == generator.ASCII_COLUMNS // 2
        assert all(len(row) == generator.ASCII_COLUMNS for row in drawing)

    def test_it_is_drawn_in_weights_not_in_blocks(self, generator):
        """Without colour the only thing left to carry the mark is glyph weight."""
        drawn = {character for row in _drawing(generator) for character, _colour in row}

        assert drawn <= set("O#+:. ")
        assert "O" in drawn, "the buttons are not drawn"
        assert "#" in drawn, "the ring is not drawn"

    def test_a_run_is_one_colour_and_the_runs_cover_the_row(self, generator):
        """The installer splits runs and prints them; it never counts columns."""
        for row in _drawing(generator):
            encoded = generator.runs(list(row), generator.ASCII_COLUMNS)
            runs = encoded.split(generator.RUN_SEPARATOR)
            rebuilt = "".join(run.split(":", 1)[1] for run in runs)

            assert rebuilt == "".join(character for character, _colour in row)
            assert len(rebuilt) == generator.ASCII_COLUMNS

    def test_the_two_tones_come_from_the_palette_the_build_ships(self, generator):
        """A drawing in colours the mark is not in is a different mark."""
        gen = _load(_REPO_ROOT / "scripts" / "logo" / "gen.py", "gen")

        _ring, button = generator.tones()

        assert button == gen.BY_NAME[gen.CHOSEN].dot_peach


class TestEveryToneIsThePalettes:
    """No colour written down here, so a change of palette cannot leave one behind."""

    def test_every_tone_the_block_declares_is_a_shipped_one(self, generator):
        gen = _load(_REPO_ROOT / "scripts" / "logo" / "gen.py", "gen")
        palette = gen.BY_NAME[gen.CHOSEN]
        shipped = {*palette.disc, *palette.ink, palette.dot_tan, palette.dot_peach}

        ring, button = generator.tones()

        assert {ring, button, generator.disc_tone()} <= shipped

    def test_the_wordmark_is_drawn_in_one_of_them(self, generator):
        """Its opaque middle is the fill exactly; only its edge is blended."""
        drawn = {colour for row in generator.wordmark_cells() for _character, *pair in row for colour in pair if colour}
        fill = tuple(int(generator.disc_tone()[index : index + 2], 16) for index in (1, 3, 5))

        assert fill in drawn

    def test_the_source_writes_no_colour_down(self, generator):
        """The one way a tone gets left behind is a literal, so there are none."""
        source = (_REPO_ROOT / "scripts" / "logo" / "terminal.py").read_text(encoding="utf-8")
        literals = re.findall(r'["\']#[0-9a-fA-F]{6}["\']', source)

        assert literals == [], f"a colour is written down rather than read: {literals}"


class TestTheWordmark:
    def test_it_is_the_size_it_was_approved_at(self, generator):
        rows = generator.wordmark_cells()

        assert len(rows) == generator.WORDMARK_ROWS
        assert all(len(row) == generator.WORDMARK_COLUMNS for row in rows)

    def test_its_plain_form_still_spells_the_word(self, generator):
        """A diff can read it; that is the whole reason the second file exists."""
        plain = generator.wordmark_plain()

        assert plain.count("\n") == generator.WORDMARK_ROWS
        assert any(line.strip() for line in plain.splitlines())


class TestTheColourMapping:
    def test_the_nearest_256_index_is_the_nearest_one(self, generator):
        """Exact cube corners, and a grey that is not in the cube at all."""
        assert generator.nearest_256((0, 0, 0)) == 16
        assert generator.nearest_256((255, 255, 255)) == 231
        assert generator.nearest_256((8, 8, 8)) == 232
